import requests
from bs4 import BeautifulSoup

"""From http://www.asx.com.au/asx/research/companyInfo.do we know that these are the GICS codes lised on the ASX."""

ASX_INDUSTRIES = {
    "1010": "Energy",
    "1510": "Materials",
    "2010": "Capital Goods",
    "2020": "Commercial & Professional Services",
    "2030": "Transportation",
    "2510": "Automobile & Components",
    "2520": "Consumer Durables & Apparel",
    "2530": "Consumer Services",
    "2540": "Media",
    "2550": "Retailing",
    "3010": "Food & Staples Retailing",
    "3020": "Food Beverage & Tobacco",
    "3030": "Household & Personal Products",
    "3510": "Health Care Equipment & Services",
    "3520": "Pharmaceuticals, Biotechnology & Life Sciences",
    "4010": "Banks",
    "4020": "Diversified Financials",
    "4030": "Insurance",
    "4040": "Real Estate",
    "4510": "Software & Services",
    "4520": "Technology Hardware & Equipment",
    "4530": "Semiconductors & Semiconductor Equipment",
    "5010": "Telecommunication Services",
    "5510": "Utilities",
}

"""For each GICS code we may extract a list of appropriate companies at a URL like
http://www.asx.com.au/asx/research/companyInfo.do?by=industryGroup&industryGroup=2530
Then we look for a list of companies ina a "select" field named "asxCode".
"""
GICS_URL_TEMPLATE = "http://www.asx.com.au/asx/research/companyInfo.do?by=industryGroup&industryGroup=%s"

ALL_INDUSTRY_FIRMS = {}

def get_codes():
    global ALL_INDUSTRY_FIRMS
    for gics_code in ASX_INDUSTRIES.keys():
        companies = {}
        r = requests.get(GICS_URL_TEMPLATE % gics_code)
        bs=BeautifulSoup(r.content)
        company_fields = bs.find("select", {'name':"asxCode"}).findAll("option")
        # Note that at the moment this doesn't regex out the weird company text that ACTUALLY looks like, e.g.
        #'EPX': u'(ETHANE PIPELINE)',
        
        for company in company_fields:
            companies[company.attrs['value']] = company.text
        ALL_INDUSTRY_FIRMS[gics_code] = companies
    return ALL_INDUSTRY_FIRMS

ALL_INDUSTRY_FIRMS = \
{'1010': {'AAE': u'AGRI ENERGY LIMITED',
          'AAL': u'APAC COAL',
          'ACB': u'A-CAP RESOURCES',
          'ACN': u'ACER ENERGY LIMITED',
          'ADD': u'ADAVALE RESOURCE LTD',
          'ADX': u'ADX ENERGY LTD',
          'AEB': u'ALGAE.TEC LIMITED',
          'AED': u'AED OIL LIMITED',
          'AEE': u'AURA ENERGY',
          'AEM': u'ARTIST & ENTERTAIN.',
          'AFR': u'AFRICAN ENERGY RES',
          'AGE': u'ALLIGATOR ENERGY',
          'AHQ': u'ALLEGIANCE COAL LTD',
          'AJC': u'ACACIA COAL LTD',
          'AJQ': u'ARMOUR ENERGY LTD',
          'AKK': u'AUSTIN EXPLORATION',
          'AMU': u'AMADEUS ENERGY',
          'AOC': u'AUSTRALIAN OIL CO.',
          'AOK': u'AUSTEX OIL LIMITED',
          'AQA': u'AQUILA RESOURCES',
          'AQO': u'AMBASSADOR OIL GAS',
          'ARW': u'AUSTRALIAN RENEWABLE',
          'AUT': u'AURORA OIL & GAS',
          'AVD': u'ADVANCE ENERGY',
          'AWE': u'AWE LIMITED',
          'AYE': u'AVOCET RES LTD',
          'AZZ': u'ANTARES ENERGY LTD',
          'BAC': u'BARU RESOURCES LTD',
          'BAS': u'BASS STRAIT OIL CO',
          'BCC': u'BUCCANEER ENERGY LTD',
          'BCR': u'BLACKCREST RES LTD',
          'BGG': u'BLACKGOLD INT HLDGS',
          'BKP': u'BARAKA ENERGY RES',
          'BKY': u'BERKELEY RESOURCES',
          'BLK': u'BLACKHAM RESOURCES',
          'BLZ': u'BLAZE INTERNATIONAL',
          'BMN': u'BANNERMAN RESOURCES',
          'BND': u'BANDANNA ENERGY',
          'BNT': u'BOUNTY MINING LTD',
          'BOE': u'BOSS RESOURCES LTD',
          'BPT': u'BEACH ENERGY LIMITED',
          'BRU': u'BURU ENERGY',
          'BUL': u'BLUE ENERGY LIMITED',
          'BUR': u'BURLESON ENERGY',
          'BUY': u'BOUNTY OIL & GAS NL',
          'BWN': u'BOWEN ENERGY LIMITED',
          'CBQ': u'COALBANK LIMITED',
          'CCC': u'CONTINENTAL COAL LTD',
          'CCJ': u'COUNTY COAL LTD',
          'CEL': u'CHALLENGER ENERGY',
          'CES': u'COAL FE RESOURCES',
          'CGV': u'CLEAN GLOBAL ENERGY',
          'CIG': u'CASPIAN OIL & GAS',
          'CKK': u'CORETRACK LIMITED',
          'CLR': u'CARABELLA RES LTD',
          'CNX': u'CARBON ENERGY',
          'COE': u'COOPER ENERGY LTD',
          'COI': u'COMET RIDGE LIMITED',
          'COK': u'COCKATOO COAL',
          'CPL': u'COALSPUR MINES LTD',
          'CPN': u'CARPATHIAN RESOURCES',
          'CQC': u'CUESTA COAL LTD',
          'CRM': u'CARBON MINERALS LTD',
          'CTP': u'CENTRAL PETROLEUM',
          'CTX': u'CALTEX AUSTRALIA',
          'CUE': u'CUE ENERGY RESOURCE',
          'CUU': u'CALLABONNA URANIUM',
          'CUX': u'CROSSLAND URANIUM',
          'CUY': u'CURNAMONA ENERGY LTD',
          'CVN': u'CARNARVON PETROLEUM',
          'CWK': u'COALWORKS LIMITED',
          'CXU': u'CAULDRON ENERGY LTD',
          'CXY': u'COUGAR ENERGY',
          'DLS': u'DRILLSEARCH ENERGY',
          'DRG': u'DRAIG RESOURCES LTD',
          'DSN': u'DESERT MINES METALS',
          'DTE': u'DART ENERGY LTD',
          'DYL': u'DEEP YELLOW LIMITED',
          'EAF': u'EAST AFRICA RES LTD',
          'EDE': u'EDEN ENERGY LIMITED',
          'EEG': u'EMPIRE ENERGY LTD',
          'EER': u'EAST ENERGY RESOURCE',
          'EGO': u'EMPIRE OIL & GAS',
          'EHR': u'EARTH HEAT RES',
          'EKA': u'EUREKA ENERGY LTD',
          'ELK': u'ELK PETROLEUM',
          'EMA': u'ENERGY AND MINERALS',
          'EME': u'ENERGY METALS LTD',
          'EMR': u'EMERALD OIL & GAS NL',
          'EMX': u'ENERGIA MINERALS LTD',
          'EOC': u'ENDOCOAL LIMITED',
          'EPG': u'EUROPEAN GAS',
          'ERA': u'ENERGY RESOURCES',
          'ERN': u'ERONGO ENERGY',
          'ERO': u'ERO MINING LIMITED',
          'ESM': u'ESPERANCE MINERALS',
          'ETE': u'ENTEK ENERGY LTD',
          'EUL': u'ECLIPSE URANIUM LTD',
          'EVE': u'ENERGY VENTURES LTD',
          'EXE': u'EXOMA ENERGY LIMITED',
          'EXR': u'ELIXIR PETROLEUM LTD',
          'FAR': u'FAR LTD',
          'FSE': u'FIRESTONE ENERGY LTD',
          'GBP': u'GLOBAL PETROLEUM',
          'GBX': u'GB ENERGY LIMITED',
          'GCL': u'GLOUCESTER COAL',
          'GGE': u'GRAND GULF ENERGY',
          'GGP': u'GOLDEN GATE PETROL',
          'GGX': u'GAS2GRID LIMITED',
          'GLL': u'GALILEE ENERGY LTD',
          'GPP': u'GREENPOWER ENRGY LTD',
          'GRV': u'GREENVALE MINING NL',
          'GUF': u'GUILDFORD COAL LTD',
          'HOG': u'HAWKLEY OIL AND GAS',
          'HZN': u'HORIZON OIL LIMITED',
          'ICN': u'ICON ENERGY LIMITED',
          'ICX': u'INTERNATIONAL COAL',
          'ICZ': u'INDUS COAL LTD',
          'IDO': u'INDO MINES LIMITED',
          'IEC': u'INTRA ENERGY CORP',
          'IKW': u'IKWEZI MINING LTD',
          'IOG': u'INCREMENTAL OIL GAS',
          'JAT': u'JATENERGY LIMITED',
          'JKA': u'JACKA RESOURCES LTD',
          'JPR': u'JUPITER ENERGY',
          'KAR': u'KAROON GAS AUSTRALIA',
          'KEY': u'KEY PETROLEUM',
          'KIK': u'KAIRIKI ENERGY LTD',
          'KKO': u'KINETIKO ENERGY LTD',
          'KPL': u'KINA PETROLEUM LTD',
          'LGO': u'LONGREACH OIL LTD.',
          'LHD': u'LOCHARD ENERGY GRP',
          'LIO': u'LION ENERGY LIMITED',
          'LKO': u'LAKES OIL NL',
          'LME': u'L&M ENERGY LIMITED',
          'LMR': u'LEMUR RESOURCES LTD',
          'LNC': u'LINC ENERGY LTD',
          'LNG': u'LIQUEFIED NATURAL',
          'MAD': u'MAVERICK DRILLING',
          'MAE': u'MARION ENERGY',
          'MBT': u'MISSION NEWENERGY',
          'MCE': u'MATRIX C & E LTD',
          'MEL': u'METGASCO LIMITED',
          'MEO': u'MEO AUSTRALIA LTD',
          'MEU': u'MARMOTA ENERGY LTD',
          'MGN': u'MAGELLAN PETROLEUM.',
          'MHC': u'MANHATTAN CORP LTD',
          'MIO': u'MICLYN EXP OFFSHR',
          'MKE': u'MAKO HYDROCARBON LTD',
          'MMR': u'MEC RESOURCES',
          'MOG': u'MOBY OIL & GAS LTD',
          'MOU': u'MODUN RESOURCES LTD',
          'MOZ': u'MOZAMBI COAL LIMITED',
          'MPO': u'MOLOPO ENERGY LTD',
          'MTE': u'METROCOAL LIMITED',
          'NAE': u'NEW AGE EXPLORATION',
          'NDO': u'NIDO PETROLEUM',
          'NEN': u'NEON ENERGY LIMITED',
          'NFL': u'NATURAL FUEL LIMITED',
          'NGE': u'NEW GUINEA ENERGY',
          'NGY': u'NUENERGY GAS LTD',
          'NHC': u'NEW HOPE CORPORATION',
          'NMS': u'NEPTUNE MARINE',
          'NRU': u'NEWERA RESOURCES LTD',
          'NSE': u'NEW STANDARD ENERGY',
          'NTU': u'NORTHERN MIN LTD',
          'NWE': u'NORWEST ENERGY NL',
          'NXS': u'NEXUS ENERGY LIMITED',
          'NZO': u'NEW ZEALAND OIL& GAS',
          'OBL': u'OIL BASINS LIMITED',
          'ODN': u'ODIN ENERGY LIMITED',
          'ODY': u'ODYSSEY ENERGY',
          'OEG': u'ORPHEUS ENERGY LTD',
          'OEL': u'OTTO ENERGY LIMITED',
          'OEX': u'OILEX LTD',
          'OGL': u'OGL RESOURCES LTD',
          'OGY': u'ORCA ENERGY LIMITED',
          'OKU': u'OKLO RESOURCES LTD',
          'OMX': u'ORMIL ENERGY LIMITED',
          'ORG': u'ORIGIN ENERGY',
          'OSH': u'OIL SEARCH LTD',
          'OTE': u'OTIS ENERGY LIMITED',
          'OXX': u'OCTANEX N.L.',
          'PAX': u'PANAX GEOTHERMAL LTD',
          'PCL': u'PANCONTINENTAL OIL',
          'PDN': u'PALADIN ENERGY LTD',
          'PGS': u'PLANET GAS LTD',
          'PPP': u'PAN PACIFIC PETROL.',
          'PRL': u'PETREL ENERGY LTD',
          'PSA': u'PETSEC ENERGY',
          'PVD': u'PURA VIDA ENERGY NL',
          'PVE': u'PO VALLEY ENERGY LTD',
          'PXR': u'PADANG RESOURCES LTD',
          'PYM': u'PRYME ENERGY LIMITED',
          'PZC': u'PAN ASIA CORP LTD',
          'QPN': u'QUEST PETROLEUM',
          'RAI': u'RAISAMA ENERGY LTD',
          'RAW': u'RAWSON RESOURCES',
          'RCI': u'ROCKLANDS RICH. LTD',
          'RES': u'RESOURCE GENERATION',
          'REY': u'REY RESOURCES LTD',
          'REZ': u'RESOURC & EN GRP LTD',
          'RFE': u'RED FORK ENERGY',
          'RGU': u'REGALPOINT RES LTD',
          'RIA': u'RIALTO ENERGY',
          'RMP': u'RED EMPEROR RESOURCE',
          'ROC': u'ROC OIL COMPANY',
          'ROG': u'RED SKY ENERGY.',
          'RRS': u'RANGE RESOURCES LTD',
          'RUM': u'RUM JUNGLE RES',
          'SBI': u'STERLING BIOFUELS',
          'SEA': u'SUNDANCE ENERGY',
          'SEH': u'SINO GAS ENERGY',
          'SER': u'STRATEGIC ENERGY',
          'SGY': u'SOLIMAR ENERGY LTD',
          'SLT': u'SELECT VACCINES',
          'SNE': u'SOMERTON ENERGY',
          'SNY': u'SUNBIRD ENERGY LTD',
          'SPS': u'SPRINT ENERGY LTD',
          'SSN': u'SAMSON OIL & GAS LTD',
          'STO': u'SANTOS LTD',
          'STX': u'STRIKE ENERGY LTD',
          'SUR': u'SUN RESOURCES NL',
          'SWW': u'SWW ENERGY LIMITED',
          'SXY': u'SENEX ENERGY LIMITED',
          'SYS': u'SYNGAS LIMITED',
          'TAP': u'TAP OIL LIMITED',
          'TDO': u'3D OIL LIMITED',
          'TEG': u'TRIANGLE ENERGY LTD',
          'TEU': u'TOP END URANIUM LTD',
          'TEX': u'TARGET ENERGY',
          'TMK': u'TAMASKA OIL GAS LTD',
          'TNP': u'TRIPLE ENERGY LTD',
          'TOE': u'TORO ENERGY LIMITED',
          'TPL': u'TPL CORPORATION LTD',
          'TPT': u'TANGIERS PETROLEUM',
          'TSV': u'TRANSERV ENERGY LTD',
          'TTE': u'TITAN ENERGY LTD',
          'TTN': u'TITAN ENERGY SERVICE',
          'TXN': u'TEXON PETROLEUM LTD',
          'UEQ': u'URANIUM EQUITIES',
          'UNV': u'UNIVERSAL COAL PLC',
          'UNX': u'URANEX LIMITED',
          'USA': u'URANIUMSA LIMITED',
          'UUL': u'UNITED URANIUM',
          'UXA': u'UXA RESOURCES LTD',
          'WAL': u'WAVENET INTERNATION.',
          'WCL': u'WESTSIDE CORPORATION',
          'WEC': u'WHITE ENERGY COMPANY',
          'WHC': u'WHITEHAVEN COAL',
          'WHE': u'WILDHORSE ENERGY',
          'WHN': u'WHL ENERGY LIMITED',
          'WOR': u'WORLEYPARSONS LTD',
          'WPL': u'WOODSIDE PETROLEUM',
          'XCD': u'XCEED RES LTD',
          'XST': u'XSTATE RESOURCES',
          'ZTA': u'ZETA PETROLEUM'},
 '1510': {'AAI': u'ALCOA INC.',
          'AAJ': u'ARUMA RESOURCES LTD',
          'AAR': u'ANGLO AUSTRALIAN',
          'ABC': u'ADELAIDE BRIGHTON',
          'ABU': u'ABM RESOURCES NL',
          'ABY': u'ADITYA BIRLA',
          'ABZ': u'AUST BAUXITE LTD',
          'ACP': u'AUDALIA RES LTD',
          'ACS': u'ACCENT RESOURCES NL',
          'ADN': u'ADELAIDE RESOURCES',
          'ADY': u'ADMIRALTY RESOURCES.',
          'AEK': u'ANATOLIA ENERGY LTD',
          'AGD': u'AUSTRAL GOLD',
          'AGG': u'ANGLOGOLD ASHANTI',
          'AGO': u'ATLAS IRON LIMITED',
          'AGR': u'AGUIA RES LTD',
          'AGS': u'ALLIANCE RESOURCES',
          'AGU': u'AURIUM RESOURCES',
          'AGY': u'ARGOSY MINERALS LTD',
          'AHK': u'ARK MINES LIMITED',
          'AHN': u'ATHENA RESOURCES',
          'AHR': u'ANCHOR RESOURCES',
          'AIV': u'ACTIVEX LIMITED',
          'AIW': u'AUSAMERICAN MIN CORP',
          'AJM': u'ALTURA MINING LTD',
          'AJX': u'ALEXIUM INT GROUP',
          'AKA': u'AUST MINERALS MINING',
          'AKM': u'ASPIRE MINING LTD',
          'ALB': u'ALBIDON LIMITED',
          'ALD': u'ALLIED GOLD MIN PLC',
          'ALK': u'ALKANE RESOURCES LTD',
          'ALY': u'ALCHEMY RESOURCE LTD',
          'AMC': u'AMCOR LIMITED',
          'AMX': u'AMPELLA MINING',
          'ANO': u'ANTARIA LIMITED',
          'ANW': u'AUSNICO LIMITED',
          'AOA': u'AUSMON RESORCES',
          'AOH': u'ALTONA MINING LTD',
          'AOM': u'AUSTRALIA ORIENTAL',
          'AON': u'APOLLO MINERALS LTD',
          'AOP': u'APOLLO CONSOLIDATED',
          'APG': u'AUSTPAC RESOURCES NL',
          'AQC': u'AUSPACCOAL LTD',
          'AQD': u'AUSQUEST LIMITED',
          'AQG': u'ALACER GOLD CORP.',
          'AQP': u'AQUARIUS PLATINUM.',
          'AQQ': u'APHRODITE GOLD LTD',
          'AQR': u'AUSSIE Q RESOURCES',
          'ARD': u'ARGENT MINERALS',
          'ARE': u'ARGONAUT RESOURCES',
          'ARH': u'AUSTRALASIAN RESOUR.',
          'ARM': u'AURORA MINERALS LTD',
          'ARO': u'ASTRO RESOURCES NL',
          'ARU': u'ARAFURA RESOURCE LTD',
          'ARV': u'ARTEMIS RESOURCES',
          'ARX': u'ARC EXPLORATION LTD',
          'ATI': u'ATLANTIC LIMITED',
          'ATM': u'ANEKA TAMBANG',
          'ATN': u'ASHBURTON MINERALS',
          'ATR': u'ASTRON CORP LTD',
          'ATV': u'ATLANTIC GOLD NL',
          'AUC': u'AUSGOLD LIMITED',
          'AUK': u'AUGUR RESOURCES LTD',
          'AUQ': u'ALARA RESOURCES LTD',
          'AUV': u'AUSTRALIS MINING',
          'AUZ': u'AUSTRALIAN MINES LTD',
          'AVA': u'AVIVA CORPORATION',
          'AVB': u'AVANCO RESOURCES LTD',
          'AVI': u'AVALON MINERALS',
          'AVK': u'ARGENTINA MINING LTD',
          'AVQ': u'AXIOM MINING LIMITED',
          'AVY': u'AVENUE RESOURCES LTD',
          'AVZ': u'AVONLEA MINERALS',
          'AWC': u'ALUMINA LIMITED',
          'AWD': u'ALEATOR ENERGY LTD',
          'AXC': u'AXG MINING LTD',
          'AXE': u'ARCHER EXPLORATION',
          'AXM': u'APEX MINERALS NL',
          'AXT': u'ARGO EXPLORATION',
          'AXZ': u'AMEX RESOURCES',
          'AYA': u'ATTILA RESOURCES LTD',
          'AYB': u'AUSTRALIAN PROTEINS',
          'AYC': u'A1 GOLD LTD',
          'AYM': u'ALTIUS MINING LTD',
          'AYN': u'ALCYONE RES LTD',
          'AYR': u'ALLOY RESOURCES',
          'AZC': u'AUSTRALIAN ZIRCON NL',
          'AZH': u'AZIMUTH RES LTD',
          'AZK': u'AZIANA LIMITED',
          'AZM': u'AZUMAH RESOURCES',
          'AZS': u'AZURE MINERALS',
          'AZY': u'ANTIPA MINERALS LTD',
          'BAB': u'BULLABULLING GOLD',
          'BAR': u'BARRA RESOURCES',
          'BAU': u'BAUXITE RESOURCE LTD',
          'BBR': u'BORA BORA RESOURCES',
          'BBX': u'BBX MINERALS LTD',
          'BCD': u'BCD RESOURCES NL',
          'BCI': u'BC IRON LIMITED',
          'BCN': u'BEACON MINERALS',
          'BDI': u'BLINA MINERALS NL',
          'BDR': u'BEADELL RESOURCE LTD',
          'BFE': u'BLACK FIRE MINERALS',
          'BGD': u'BOULDER STEEL',
          'BGH': u'BLIGH RESOURCES LTD',
          'BGS': u'BIRIMIAN GOLD LTD',
          'BHP': u'BHP BILLITON LIMITED',
          'BHU': u'BEACON HILL RES PLC',
          'BIS': u'BISALLOY STEEL',
          'BKW': u'BRICKWORKS LIMITED',
          'BLD': u'BORAL LIMITED.',
          'BLR': u'BLACK RANGE MIN.',
          'BMB': u'BALAMARA RESOURCES',
          'BMG': u'BRAZILIAN METAL GRP.',
          'BML': u'BOTSWANA METALS LTD',
          'BMY': u'BRUMBY RESOURCES',
          'BMZ': u'BLACK MOUNTA RES LTD',
          'BNR': u'BULLETIN RES LTD',
          'BOC': u'BOUGAINVILLE COPPER',
          'BPL': u'BROKEN HILL PROSPECT',
          'BRB': u'BREAKER RES NL',
          'BRD': u'BLACK RIDGE MIN NL',
          'BRM': u'BROCKMAN RESOURCES',
          'BRW': u'BREAKAWAY RESOURCES',
          'BSE': u'BASE RES LIMITED',
          'BSL': u'BLUESCOPE STEEL LTD',
          'BSM': u'BASS METALS LTD',
          'BSR': u'BASSARI RESOURCES',
          'BTN': u'BRIGHTON MINING',
          'BTR': u'BLACKTHORN RESOURCES',
          'BTU': u'BATHURST RESOURCES',
          'BUT': u'BRIGHT STAR RES LTD',
          'BUX': u'BUXTON RESOURCES LTD',
          'BWD': u'BLACKWOOD CORP LTD',
          'BYR': u'BUREY GOLD LIMITED',
          'BZL': u'BRAZIRON LIMITED',
          'CAA': u'CAPRAL LIMITED',
          'CAP': u'CARPENTARIA EXP. LTD',
          'CAS': u'CRUSADER RESOURCES',
          'CAV': u'CARNAVALE RESOURCES',
          'CAY': u'CANYON RESOURCES LTD',
          'CAZ': u'CAZALY RESOURCES',
          'CBS': u'CABRAL RESOURCES LTD',
          'CBX': u'CAPE ALUMINA LTD',
          'CCU': u'COBAR CONSOLIDATED',
          'CDB': u'CONDOR BLANCO MINES',
          'CDG': u'CLEVELAND MIN LTD',
          'CDH': u'CHONGHERR INVESTMENT',
          'CDT': u'CASTLE MINERALS',
          'CDU': u'CUDECO LIMITED',
          'CFE': u'CAPE LAMBERT RES LTD',
          'CGI': u'CONSOLIDATED GLOBAL',
          'CGM': u'COUGAR METALS NL',
          'CGT': u'CASTLEMAINE',
          'CGU': u'COMMISSIONERS GOLD',
          'CGX': u'CGA MINING LIMITED',
          'CHK': u'COHIBA MIN LTD',
          'CHN': u'CHALICE GOLD MINES',
          'CHZ': u'CHESSER RESOURCES',
          'CII': u'CI RESOURCES LIMITED',
          'CJO': u'CERRO RESOURCES NL',
          'CKA': u'COKAL LTD',
          'CKL': u'COLORPAK LIMITED',
          'CLY': u'CLANCY EXPLORATION',
          'CMC': u'CHINA MAGNESIUM CORP',
          'CMR': u'COMPASS RESOURCES',
          'CMY': u'CAPITAL MINING',
          'CNH': u'CHINA STEEL',
          'CNK': u'CONDOR METALS LTD',
          'CNL': u'CELAMIN HOLDINGS NL',
          'CNN': u'CARDIA BIOPLASTICS',
          'CNO': u'CONTO RESOURCES LTD',
          'CNQ': u'CARBINE TUNGSTEN',
          'CNS': u'CENTIUS GOLD LIMITED',
          'COY': u'COPPERMOLY LIMITED',
          'CPD': u'CONDOTO PLATINUM NL',
          'CRB': u'CARBINE RESOURCES',
          'CRC': u'CORTONA RESOURCES',
          'CRJ': u'COPPER RANGE LIMITED',
          'CRK': u'CARRICK GOLD LIMITED',
          'CRL': u'COMET RESOURCES',
          'CRQ': u'CREDO RES LTD',
          'CSD': u'CONSOLIDATED TIN MIN',
          'CSE': u'COPPER STRIKE LTD',
          'CTM': u'CENTAURUS METALS LTD',
          'CTO': u'CITIGOLD CORP LTD',
          'CUG': u'CRUCIBLE GOLD LTD',
          'CUL': u'CULLEN RESOURCES',
          'CVE': u'COVE RESOURCES LTD',
          'CVG': u'CONVERGENT MINERALS',
          'CVR': u'CENTRAL ASIA RES',
          'CVY': u'COVENTRY RESOURCES',
          'CWG': u'CENTRAL WEST GOLD NL',
          'CWH': u'CWH RESOURCES LTD',
          'CXM': u'CENTREX METALS',
          'CXO': u'CORE EXPLORATION LTD',
          'CXX': u'CRADLE RESOURCES LTD',
          'CYL': u'CATALYST METALS',
          'CYS': u'CHRYSALIS RESOURCES',
          'CYU': u'CHINALCO YUNNAN',
          'CZA': u'COAL OF AFRICA LTD',
          'CZI': u'CASSINI RESOURCES',
          'CZN': u'CORAZON LTD',
          'CZR': u'COZIRON RESOURCES',
          'DAU': u'DAMPIER GOLD LTD',
          'DDD': u'3D RESOURCES LIMITED',
          'DEG': u'DE GREY MINING',
          'DGO': u'DRUMMOND GOLD LTD',
          'DGR': u'DGR GLOBAL LTD',
          'DIS': u'DISCOVERY RES LTD',
          'DLE': u'DRAGON ENERGY',
          'DLX': u'DULUXGROUP LIMITED',
          'DMA': u'DYNASTY METALS',
          'DMG': u'DRAGON MOUNTAIN GOLD',
          'DMI': u'DEMPSEY MINERALS',
          'DML': u'DISCOVERY METALS LTD',
          'DON': u'DIAMONEX LIMITED',
          'DRA': u'DRAGON MINING LTD',
          'DRK': u'DRAKE RESOURCES',
          'DRM': u'DORAY MINERALS LTD',
          'DRX': u'DIATREME RESOURCES',
          'DTG': u'DATON GRP AUS LTD',
          'DTM': u'DART MINING NL',
          'DUO': u'DOURADO RES LTD',
          'EAR': u'ECHO RESOURCES',
          'EAU': u'ELDORADO GOLD CORP',
          'EFE': u'EASTERN IRON',
          'EIO': u'ENERGIO LIMITED',
          'ELM': u'ELEMENTAL MINERALS',
          'ELT': u'ELEMENTOS LIMITED',
          'EMG': u'EMERGENT RESOURCES',
          'EMU': u'EMU NICKEL NL',
          'ENK': u'ENK PLC',
          'ENL': u'EAGLE NICKEL LTD',
          'ENR': u'ENCOUNTER RESOURCES',
          'ENT': u'ENTERPRISE METALS',
          'EPC': u'EPIC RESOURCES LTD',
          'EQU': u'EQUATOR RESOURCES',
          'EQX': u'EQUATORIAL RES LTD',
          'ERD': u'EXALT RESOURCES LTD',
          'ERL': u'EMPIRE RESOURCES',
          'ERM': u'EMMERSON RESOURCES',
          'ESR': u'ESTRELLA RES LTD',
          'EUG': u'EUROGOLD LIMITED',
          'EUM': u'EUMERALLA RESOURCES',
          'EVN': u'EVOLUTION MINING LTD',
          'EVR': u'ENDEAVOUR MIN CORP',
          'EXC': u'EXTERRA RES LTD',
          'EXG': u'EXCELSIOR GOLD LTD',
          'EXM': u'EXCALIBUR MINING',
          'EXS': u'EXCO RESOURCES LTD',
          'FAS': u'FAIRSTAR RESOURCES',
          'FBU': u'FLETCHER BUILDING',
          'FCN': u'FALCON MINERALS LTD',
          'FCR': u'FERRUM CRESCENT LTD',
          'FEL': u'FE LIMITED',
          'FEO': u'FEORE LIMITED',
          'FIE': u'FIRESTRIKE RES LTD',
          'FIS': u'FISSION ENERGY',
          'FMG': u'FORTESCUE METALS GRP',
          'FMJ': u'FORTIS MINING LTD',
          'FML': u'FOCUS MINERALS LTD',
          'FMS': u'FLINDERS MINES LTD',
          'FND': u'FINDERS RESOURCES',
          'FNT': u'FRONTIER RESOURCES',
          'FOY': u'FOYSON RESOURCES LTD',
          'FRC': u'FORTE CONSOLIDATED',
          'FRG': u'FORGE RESOURCES LTD',
          'FRY': u'FITZROY RES LTD',
          'FTE': u'FORTE ENERGY NL',
          'FWL': u'FERROWEST LIMITED',
          'FXR': u'FOX RESOURCES',
          'FYI': u'FYI RESOURCES LTD',
          'GBE': u'GLOBE METALS &MINING',
          'GBG': u'GINDALBIE METALS LTD',
          'GBM': u'GBM GOLD LTD',
          'GBZ': u'GBM RSOURCES LTD',
          'GCR': u'GOLDEN CROSS',
          'GCY': u'GASCOYNE RES LTD',
          'GDA': u'GONDWANA RESOURCES',
          'GDO': u'GOLD ONE INT LTD',
          'GED': u'GOLDEN DEEPS',
          'GES': u'GENESIS RESOURCES',
          'GGG': u'GREENLAND MIN EN LTD',
          'GIP': u'GIPPSLAND LIMITED',
          'GLA': u'GLADIATOR RESOURCES',
          'GLF': u'GULF IND LTD',
          'GLM': u'GULF MINES LIMITED',
          'GLN': u'GLENEAGLE GOLD',
          'GLY': u'GLORY RESOURCES LTD',
          'GMD': u'GENESIS MINERALS',
          'GME': u'GME RESOURCES LTD',
          'GML': u'GATEWAY MINING',
          'GMM': u'GENERAL MINING CORP',
          'GMR': u'GOLDEN RIM RESOURCES',
          'GMX': u'GOLDMINEX RESOURCES',
          'GNM': u'GUJARAT NRE COAL LTD',
          'GNS': u'GUNNS LIMITED',
          'GOA': u'GOLD ANOMALY LIMITED',
          'GOR': u'GOLD ROAD RES LTD',
          'GPH': u'GOLDPHYRE RES LTD',
          'GPR': u'GEOPACIFIC RESOURCES',
          'GRM': u'GLOBAL RES CORP LTD',
          'GRR': u'GRANGE RESOURCES.',
          'GRX': u'GOODRICH RES LTD',
          'GRY': u'GRYPHON MINERALS LTD',
          'GSC': u'GLOBAL GEOSCIENCE',
          'GSE': u'GOLDSEARCH LIMITED',
          'GSZ': u'GLOBAL STRAT MET',
          'GTE': u'GREAT WESTERN EXP.',
          'GTR': u'GTI RESOURCES',
          'GUL': u'GULLEWA LIMITED',
          'GUN': u'GUNSON RESOURCES',
          'GWR': u'GOLDEN WEST RESOURCE',
          'GXN': u'GLOBAL METALS',
          'GXY': u'GALAXY RESOURCES',
          'HAO': u'HAOMA MINING NL',
          'HAR': u'HARANGA RES LTD',
          'HAS': u'HASTINGS RARE METALS',
          'HAV': u'HAVILAH RESOURCES NL',
          'HAW': u'HAWTHORN RESOURCES',
          'HAZ': u'HAZELWOOD RESOURCES',
          'HCH': u'HOT CHILI LTD',
          'HDG': u'HODGES RESOURCES',
          'HEG': u'HILL END GOLD',
          'HEM': u'HEMISPHERE RESOURCES',
          'HFR': u'HIGHFIELD RES LTD',
          'HGO': u'HILLGROVE RES LTD',
          'HHM': u'HAMPTON HILL MINING',
          'HIG': u'HIGHLANDS PACIFIC',
          'HLX': u'HELIX RESOURCES',
          'HNR': u'HANNANS REWARD LTD',
          'HOR': u'HORSESHOE METALS LTD',
          'HRR': u'HERON RESOURCES',
          'HRS': u'HUDSON RESOURCES',
          'HSK': u'HEEMSKIRK CONSOLID.',
          'IAU': u'INTREPID MINES',
          'IBG': u'IRONBARK ZINC LTD',
          'IDC': u'INDOCHINE MINING LTD',
          'IDM': u'IDM INTERNATIONAL',
          'IFE': u'IRONCLAD MINING',
          'IGO': u'INDEPENDENCE GROUP',
          'IGR': u'INTEGRA MINING LTD.',
          'IGS': u'INT GOLDFIELDS LTD',
          'ILU': u'ILUKA RESOURCES',
          'IMA': u'IMAGE RESOURCES NL',
          'IMD': u'IMDEX LIMITED',
          'INL': u'INTEC LTD',
          'IOH': u'IRON ORE HOLDINGS',
          'IPL': u'INCITEC PIVOT',
          'IPT': u'IMPACT MINERALS',
          'IRC': u'INTERMIN RESOURCES',
          'IRD': u'IRON ROAD LTD',
          'IRG': u'INTEGRATED RESOURCES',
          'IRL': u'INDIA RESOURCES',
          'IRM': u'IRON MOUNTAIN',
          'IRN': u'INDOPHIL RESOURCES',
          'ISH': u'ISHINE INT RES',
          'ITT': u'INTERMET RESOURCES',
          'IVA': u'IVANHOE AUSTRALIA',
          'IVG': u'INVICTUS GOLD LTD',
          'IVR': u'INVESTIGATOR RES LTD',
          'IXR': u'IMX RESOURCES LTD',
          'IZM': u'INTERCEPT MINERALS',
          'JAG': u'JAGUAR MINERALS',
          'JAL': u'JAMESON RESOURCES',
          'JHX': u'JAMES HARDIE INDUST',
          'JMS': u'JUPITER MINES',
          'JRL': u'JINDALEE RESOURCES',
          'JRV': u'JERVOIS MINING',
          'KAB': u'KABOKO MINING LTD',
          'KAS': u'KASBAH RESOURCES',
          'KBL': u'KBL MINING LIMITED',
          'KCN': u'KINGSGATE CONSOLID.',
          'KDR': u'KIDMAN RESOURCES LTD',
          'KGD': u'KULA GOLD LIMITED',
          'KGL': u'KENTOR GOLD LIMITED',
          'KIS': u'KING ISLAND',
          'KMC': u'KALGOORLIE MINING',
          'KMR': u'KUMARINA RES LTD',
          'KNL': u'KIBARAN NICKEL LTD',
          'KOR': u'KORAB RESOURCES',
          'KOV': u'KORVEST LTD',
          'KPR': u'KUPANG RESOURCES',
          'KRA': u'KILLARA RESOURCES',
          'KRB': u'KRUCIBLE METALS LTD',
          'KRE': u'KIM RARE EARTHS LTD',
          'KRL': u'KANGAROO RES LTD',
          'KRM': u'KINGSROSE MINING LTD',
          'KSO': u'KING SOLOMON MINES',
          'KZL': u'KAGARA LTD',
          'LAT': u'LATIN GOLD LIMITED',
          'LBY': u'LIBERTY RESOURCE LTD',
          'LCR': u'LACONIA RES LTD',
          'LCY': u'LEGACY IRON ORE',
          'LEG': u'LEGEND MINING',
          'LGM': u'LUIRI GOLD LIMITED',
          'LIN': u'LINDIAN RESOURCES',
          'LKE': u'LAKE RESOURCES',
          'LMG': u'LATROBE MAGNESIUM',
          'LML': u'LINCOLN MINERALS',
          'LOM': u'LONRHO MINING LTD',
          'LRL': u'LEYSHON RESOURCES',
          'LRR': u'LEOPARD RESOURCES',
          'LRS': u'LATIN RESOURCES LTD',
          'LSA': u'LACHLAN STAR LTD',
          'LSN': u'LAWSON GOLD LTD',
          'LSR': u'LODESTAR MINERALS',
          'LTR': u'LIONTOWN RESOURCES',
          'LTX': u'LITHEX RES LTD',
          'LYC': u'LYNAS CORPORATION',
          'MAB': u'MAMBA MINERALS',
          'MAK': u'MINEMAKERS LIMITED',
          'MAN': u'MAGNA MINING NL',
          'MAR': u'MALACHITE RESOURCES',
          'MAS': u'MESA MINERALS LTD',
          'MAT': u'MATSA RESOURCES',
          'MAU': u'MAGNETIC RESOURCES',
          'MBK': u'METAL BANK LTD',
          'MBN': u'MIRABELA NICKEL LTD',
          'MCO': u'MORNING STAR GOLD NL',
          'MCR': u'MINCOR RESOURCES NL',
          'MDI': u'MIDDLE ISLAND RES',
          'MDL': u'MINERAL DEPOSITS',
          'MDO': u'MINDORO RES LTD',
          'MDS': u'MIDAS RESOURCES',
          'MDX': u'MINDAX LIMITED',
          'MEH': u'MERAH RES LTD',
          'MEI': u'METEORIC RESOURCES',
          'MEP': u'MINOTAUR EXPLORATION',
          'MET': u'MT ISA METALS',
          'MEY': u'MARENICA ENERGY LTD',
          'MFC': u'METALS FINANCE LTD',
          'MGL': u'MAGONTEC LIMITED',
          'MGO': u'MARENGO MINING',
          'MGU': u'MAGNUM MINING & EXP',
          'MGV': u'MUSGRAVE MINERALS',
          'MGX': u'MOUNT GIBSON IRON',
          'MGY': u'MALAGASY MINERALS',
          'MHM': u'MHM METALS LIMITED',
          'MKO': u'METALIKO RESOURCES',
          'MLI': u'MINTAILS LIMITED',
          'MLM': u'METALLICA MINERALS',
          'MLS': u'METALS AUSTRALIA',
          'MLX': u'METALS X LIMITED',
          'MML': u'MEDUSA MINING LTD',
          'MMW': u'MAGMA METALS LTD.',
          'MMX': u'MURCHISON METALS LTD',
          'MNB': u'MINBOS RESOURCES LTD',
          'MNC': u'METMINCO LIMITED',
          'MNE': u'MINING GROUP LTD',
          'MNM': u'MANTLE MINING CORP.',
          'MOD': u'MOD RESOURCES LTD',
          'MOL': u'MOLY MINES LIMITED',
          'MOO': u'MONTO MINERALS LTD',
          'MOX': u'MONAX MINING LIMITED',
          'MOY': u'MILLENNIUM MIN LTD',
          'MPJ': u'MINING PROJECTS',
          'MRC': u'MINERAL COMMODITIES',
          'MRP': u'MACPHERSONS RESOURCE',
          'MRQ': u'MRG METALS LIMITED',
          'MRR': u'MINREX RES NL',
          'MRX': u'MATRIX METALS',
          'MRY': u'MONTERAY MINING GRP',
          'MSC': u'MINERALS CORPORATION',
          'MSR': u'MANAS RES LTD',
          'MTB': u'MOUNT BURGESS MINING',
          'MTH': u'MITHRIL RESOURCES',
          'MTN': u'MARATHON RESOURCES',
          'MUB': u'MONGOLIAN RES CORP',
          'MUM': u'MOUNT MAGNET SOUTH',
          'MUN': u'MUNDO MINERALS',
          'MUX': u'MUNGANA GOLD LTD',
          'MWN': u'MIDWINTER RESOURC NL',
          'MXR': u'MAXIMUS RESOURCES',
          'MYG': u'MUTINY GOLD LIMITED',
          'MYN': u'MAYAN IRON CORP LTD',
          'MZI': u'MATILDA ZIRCON LTD',
          'MZM': u'MONTEZUMA MINING CO.',
          'NAD': u'NORTH AUSTRALIAN LTD',
          'NAG': u'NAGAMBIE MINING LTD',
          'NAV': u'NAVIGATOR RESOURCES',
          'NCM': u'NEWCREST MINING',
          'NCO': u'NAMIBIAN COPPER',
          'NCR': u'NUCOAL RESOURCES LTD',
          'NFE': u'NORTHERN IRON LTD',
          'NGF': u'NORTON GOLD FIELDS',
          'NGX': u'NORSEMAN GOLD',
          'NHO': u'NEW HORIZON COAL',
          'NIO': u'NICKELORE LTD',
          'NIU': u'NIUMINCO GROUP LTD',
          'NKP': u'NKWE PLATINUM',
          'NME': u'NEX METALS EXPLORAT',
          'NMG': u'NOBLE MINERAL RES',
          'NMI': u'NORTHERN MINING',
          'NML': u'NAVARRE MINERALS LTD',
          'NMR': u'NIMRODEL RESOURCES',
          'NOE': u'NOVARISE RENEW RES',
          'NPX': u'NUPLEX INDUSTRIES',
          'NRR': u'NARACOOTA RES LTD',
          'NSL': u'NSL CONSOLIDATED LTD',
          'NST': u'NORTHERN STAR',
          'NTL': u'NEW TALISMAN GOLD',
          'NTM': u'NORTHERN MANGANESE',
          'NUF': u'NUFARM LIMITED',
          'NUP': u'NUPOWER RESOURCES',
          'NVG': u'NAVAHO GOLD LIMITED',
          'NVI': u'NEVADA IRON',
          'NWF': u'NEWFIELD RESOURCES',
          'NWR': u'NORTHWEST RESOURCES',
          'NXR': u'NEMEX RESOURCES LTD',
          'NYO': u'NYOTA MINERALS LTD',
          'OGC': u'OCEANAGOLD CORP.',
          'OKJ': u'OAKAJEE CORP LTD',
          'OKL': u'OAKLAND RES LTD',
          'OMH': u'OM HOLDINGS LIMITED',
          'ORD': u'ORD RIVER RESOURCES',
          'ORE': u'OROCOBRE LIMITED',
          'ORH': u'ORH LIMITED',
          'ORI': u'ORICA LIMITED',
          'ORM': u'ORION METALS LTD',
          'ORN': u'ORION GOLD NL',
          'ORO': u'OROYA MINING LIMITED',
          'ORS': u'OCTAGONAL RES LTD',
          'ORX': u'ORREX RESOURCES',
          'OST': u'ONESTEEL LIMITED',
          'OUM': u'OUTBACK METALS',
          'OVL': u'ORO VERDE LTD',
          'OVR': u'OVERLAND RESOURCES',
          'OYM': u'OLYMPUS PACIFIC MIN',
          'OZL': u'OZ MINERALS',
          'PAN': u'PANORAMIC RESOURCES',
          'PCP': u'PARAMOUNT MINING',
          'PDI': u'PREDICTIVE DISC LTD',
          'PDM': u'PARADIGM METALS LTD',
          'PDY': u'PADBURY MINING LTD',
          'PDZ': u'PRAIRIE DOWNS METALS',
          'PEK': u'PEAK RESOURCES',
          'PEL': u'PELICAN RESOURCES',
          'PEM': u'PERILYA LIMITED',
          'PEN': u'PENINSULA ENERGY LTD',
          'PEX': u'PEEL MINING LIMITED',
          'PFM': u'PACIFIC MINING LTD',
          'PGI': u'PANTERRA GOLD LTD',
          'PGM': u'PLATINA RESOURCES',
          'PIM': u'PRIME MINERALS',
          'PIO': u'PIONEER RES LTD',
          'PIR': u'PAPILLON RES LTD',
          'PKR': u'PARKER RESOURCES NL',
          'PLA': u'PLATINUM AUSTRALIA',
          'PLH': u'PLYMOUTH MINERALS',
          'PLS': u'PILBARA MIN LTD',
          'PLV': u'PLUTON RESOURCES',
          'PLY': u'POLYMETALS MINING',
          'PMQ': u'PLANET METALS LTD',
          'PMR': u'PRECIOUS METAL RES',
          'PNA': u'PANAUST LIMITED',
          'PNE': u'PAYNES FIND GOLD LTD',
          'PNN': u'PEPINNINI MINERALS',
          'PNR': u'PACIFIC NIUGINI LTD',
          'PNX': u'PHOENIX COPPER LTD',
          'POK': u'POTASH MINERALS LTD',
          'POS': u'POSEIDON NICK LTD',
          'POZ': u'PHOSPHATE AUS LTD',
          'PPG': u'PRO-PAC PACKAGING',
          'PPY': u'PAPYRUS AUSTRALIA',
          'PRA': u'PROMESA LIMITED',
          'PRE': u'PACRIM ENERGY',
          'PRH': u'PHILLIPS RIVER LTD',
          'PRM': u'PLENTEX LIMITED',
          'PRU': u'PERSEUS MINING LTD',
          'PRW': u'PROTO RESOURCE & INV',
          'PSC': u'PROSPECT RES LTD',
          'PSF': u'PACIFIC ORE LTD',
          'PSH': u'PENRICE SODA',
          'PSP': u'PROSPERITY RESOURCES',
          'PTS': u'PLATSEARCH NL',
          'PUN': u'PEGASUS METALS',
          'PVM': u'PMI GOLD CORP',
          'PWN': u'POTASH WEST NL',
          'PWW': u'POWER RESOURCES LTD',
          'PXG': u'PHOENIX GOLD LIMITED',
          'QBL': u'QUEENSLAND BAUXITE',
          'QMG': u'QUAY MAGNESIUM LTD',
          'QMN': u'QLD MINING CORP',
          'QNL': u'QUEST MINERALS LTD',
          'QRL': u'QUINTESSENTIAL RES',
          'QUR': u'QUANTUM RESOURCES',
          'RAD': u'RADAR IRON LIMITED',
          'RAU': u'REPUBLIC GOLD LTD',
          'RBR': u'RUBICON RESOURCES',
          'RBX': u'RESOURCE BASE',
          'RCO': u'ROYALCO RESOURCES',
          'RCP': u'REDBANK COPPER LTD',
          'RDM': u'RED METAL LIMITED',
          'RDR': u'REED RESOURCES LTD',
          'RDS': u'REDSTONE RESOURCES',
          'RED': u'RED 5 LIMITED',
          'RER': u'REGAL RESOURCES',
          'RFV': u'RIFT VALLEY RES LTD',
          'RGX': u'RED GUM RES LTD',
          'RHI': u'RED HILL IRON',
          'RID': u'RIDGE RESOURCES LTD',
          'RIE': u'RIEDEL RESOURCES LTD',
          'RIM': u'RIMFIRE PACIFIC',
          'RIO': u'RIO TINTO LIMITED',
          'RLC': u'REEDY LAGOON CORP.',
          'RMG': u'RMG LIMITED',
          'RMI': u'RESOURCE MINING CORP',
          'RMR': u'RAM RESOURCES',
          'RMS': u'RAMELIUS RESOURCES',
          'RMT': u'RMA ENERGY LIMITED',
          'RMX': u'RED MOUNT MIN LTD',
          'RND': u'RAND MINING LTD',
          'RNG': u'RANGE RIVER GOLD LTD',
          'RNI': u'RESOURCE AND INVEST.',
          'RNS': u'RENAISSANCE MINERALS',
          'RNU': u'RENAISSANCE URANIUM',
          'ROL': u'ROBUST RESOURCES',
          'ROS': u'RED OCTOBER RES LTD',
          'ROY': u'ROYAL RESOURCES',
          'RRE': u'RUBIANNA RES LTD',
          'RRI': u'RICO RESOURCES LTD',
          'RRL': u'REGIS RESOURCES',
          'RRP': u'REALM RESOURCES LTD',
          'RSG': u'RESOLUTE MINING',
          'RSL': u'RESOURCE STAR LTD',
          'RSN': u'RENISON CONSOLIDATED',
          'RTR': u'RUMBLE RES LIMITED',
          'RUR': u'RURALAUS INVESTMENTS',
          'RVR': u'RED RIVER RESOURCES',
          'RWD': u'REWARD MINERALS LTD',
          'RXL': u'ROX RESOURCES',
          'RXM': u'REX MINERALS LIMITED',
          'SAR': u'SARACEN MINERAL',
          'SAT': u'STRATOS RES LTD',
          'SAU': u'SOUTHERN GOLD',
          'SAY': u'STH AMERICAN COR LTD',
          'SBL': u'SIGNATURE METALS LTD',
          'SBM': u'ST BARBARA LIMITED',
          'SBR': u'SABRE RESOURCES',
          'SBU': u'SIBURAN RES LIMITED',
          'SCI': u'SILVER CITY MINERALS',
          'SDL': u'SUNDANCE RESOURCES',
          'SEG': u'SEGUE RESOURCES',
          'SEO': u'SENTOSA MINING LTD',
          'SFR': u'SANDFIRE RESOURCES',
          'SFX': u'SHEFFIELD RES LTD',
          'SFZ': u'STH AMERICAN FERRO',
          'SGM': u'SIMS METAL MGMT LTD',
          'SGQ': u'ST GEORGE MIN LTD',
          'SGZ': u'SCOTGOLD RESOURCES',
          'SHD': u'SHERWIN IRON LTD',
          'SHE': u'STONEHENGE METALS',
          'SHH': u'SHREE MINERALS LTD',
          'SHK': u'STONE RESOURCES AUS',
          'SIH': u'SIHAYO GOLD LIMITED',
          'SIR': u'SIRIUS RESOURCES NL',
          'SKM': u'SUNSEEKER MINERALS',
          'SLR': u'SILVER LAKE RESOURCE',
          'SMC': u'STRATEGIC MINERALS',
          'SMD': u'SYNDICATED METALS',
          'SML': u'SYNERGY METALS LTD',
          'SMM': u'SUMMIT RESOURCES',
          'SMR': u'STANMORE COAL LTD',
          'SNV': u'SINOVUS MINING LTD',
          'SOC': u'SOVEREIGN GOLD',
          'SPA': u'SPENCER RES LTD',
          'SPH': u'SPHERE MINERALS LTD',
          'SPI': u'SPITFIRE RESOURCES',
          'SPM': u'SPEEWAH METALS LTD',
          'SPQ': u'SUPERIOR RESOURCES',
          'SRE': u'STIRLING RESOURCES.',
          'SRI': u'SIPA RESOURCES LTD',
          'SRK': u'STRIKE RESOURCES',
          'SRM': u'SIERRA MINING',
          'SRQ': u'STRAITS RES LTD.',
          'SRR': u'SHAW RIVER MANGANESE',
          'SRZ': u'STELLAR RESOURCES',
          'SSZ': u'SILVERSTONE RES LTD',
          'STB': u'SOUTH BOULDER MINES',
          'STK': u'STRICKLAND RESOURCES',
          'STZ': u'STRZELECKI METALS',
          'SUH': u'SOUTHERN HEM MIN',
          'SUM': u'SUMATRA COPPER&GOLD',
          'SVL': u'SILVER MINES LIMITED',
          'SVM': u'SOVEREIGN METALS',
          'SWA': u'SWAN GOLD MINING',
          'SWN': u'SILVER SWAN GROUP',
          'SWR': u'SOUTHERN CROWN RES',
          'SXG': u'SOUTHERNCROSS GOLD',
          'SXT': u'STRATUM METALS',
          'SXX': u'SOUTHERN CROSS EXPL',
          'SYM': u'SYMEX HOLDINGS',
          'SYR': u'SYRAH RESOURCES',
          'TAM': u'TANAMI GOLD NL',
          'TAR': u'TARUGA GOLD LTD',
          'TAS': u'TASMAN RESOURCES LTD',
          'TAW': u'TAWANA RESOURCES NL',
          'TBR': u'TRIBUNE RES LTD',
          'TCM': u'TIARO COAL LIMITED',
          'TFC': u'TFS CORPORATION LTD',
          'TGS': u'TIGER RESOURCES',
          'TGZ': u'TERANGA GOLD CORP',
          'THR': u'THOR MINING PLC',
          'THX': u'THUNDELARRA EXPLOR.',
          'TIG': u'TIGERS REALM COAL',
          'TKG': u'TAKORADI LIMITED',
          'TKL': u'TRAKA RESOURCES',
          'TLG': u'TALGA GOLD LTD',
          'TLM': u'TALISMAN MINING',
          'TLU': u'TELLUS RES LTD',
          'TMM': u'TASMANIA MINES LTD',
          'TMX': u'TERRAIN MINERALS',
          'TMZ': u'THOMSON RES LTD',
          'TNG': u'TNG LIMITED',
          'TNR': u'TORIAN RESOURCES NL',
          'TNV': u'TERRANOVA MINERALS',
          'TON': u'TRITON GOLD LTD',
          'TPR': u'TIMPETRA RESOURCES',
          'TRF': u'TRAFFORD RESOURCES',
          'TRM': u'TRUSCOTT MINING CORP',
          'TRO': u'TRIAUSMIN LIMITED',
          'TRY': u'TROY RESOURCES LTD',
          'TUC': u'TUC RESOURCES LTD',
          'TZN': u'TERRAMIN AUSTRALIA.',
          'UCL': u'UCL RESOURCES LTD',
          'UML': u'UNITY MINING LTD',
          'UOG': u'UNITED OROGEN',
          'VEC': u'VECTOR RESOURCES LTD',
          'VGO': u'VANTAGE GOLDFIELDS',
          'VII': u'VIETNAM INDUSTRIAL',
          'VKA': u'VIKING ASH',
          'VMC': u'VENUS METALS COR LTD',
          'VML': u'VITAL METALS LIMITED',
          'VMS': u'VENTURE MINERALS',
          'VOR': u'VOYAGER RESOURCES',
          'VRE': u'VIEW RESOURCES LTD',
          'VRX': u'VENTNOR RES LTD',
          'VTM': u'VOLTA MINING LTD',
          'VWM': u'VICTORY WEST METALS',
          'VXR': u'VENTUREX RESOURCES',
          'WAC': u'WILD ACRE METALS LTD',
          'WAF': u'WEST AFRICAN RES LTD',
          'WCN': u'WHITE CLIFF MIN LTD',
          'WCP': u'WCP RESOURCES LTD',
          'WDR': u'WESTERN DESERT RES.',
          'WFE': u'WINMAR RESOURCES LTD',
          'WGO': u'WARATAH RESOURCES',
          'WGR': u'WESTGOLD RESOURCES',
          'WLF': u'WOLF MINERALS',
          'WLR': u'WORLD OIL RESOURCES',
          'WMN': u'WEST MANGANESE',
          'WPG': u'WPG RES LTD',
          'WPI': u'WEST PEAK IRON LTD',
          'WRM': u'WHITE ROCK MIN LTD',
          'WSA': u'WESTERN AREAS NL',
          'WSR': u'WHITESTAR RES LTD',
          'WTR': u'WORLD TITANIUM RES',
          'WVL': u'WINDIMURRA VANADIUM',
          'WWI': u'WEST WITS MINING LTD',
          'XAM': u'XANADU MINES LTD',
          'YRR': u'YELLOW ROCK',
          'YTC': u'YTC RESOURCES',
          'ZAM': u'ZAMANCO MINERALS LTD',
          'ZGM': u'ZAMIA METALS',
          'ZIM': u'ZIMPLATS HOLDING LTD',
          'ZNC': u'ZENITH MINERALS LTD',
          'ZRI': u'RIO TINTO PLC',
          'ZRL': u'ZAMBEZI RESOURCES',
          'ZYL': u'ZYL LIMITED'},
 '2010': {'AAX': u'AUSENCO LIMITED',
          'ADQ': u'ADG GLOBAL SUPPLY.',
          'AFT': u'AFT CORPORATION',
          'AHJ': u'AIR CHANGE INT LTD',
          'AIR': u'ASTIVITA RENEWABLES',
          'AJL': u'AJ LUCAS GROUP',
          'ALS': u'ALESCO CORPORATION',
          'ANG': u'AUSTIN ENGINEERING',
          'ASB': u'AUSTAL LIMITED',
          'ASL': u'AUSDRILL LIMITED',
          'BKN': u'BRADKEN LIMITED',
          'BLY': u'BOART LONGYEAR',
          'BOL': u'BOOM LOGISTICS',
          'BPK': u'BREMER PARK LIMITED',
          'BYL': u'BRIERTY LIMITED',
          'CAQ': u'CELL AQUACULTURE',
          'CBD': u'CBD ENERGY LIMITED',
          'CDD': u'CARDNO LIMITED',
          'CFU': u'CERAMIC FUEL CELLS',
          'CLO': u'CLOUGH LIMITED',
          'CMI': u'CMI LIMITED.',
          'CSR': u'CSR LIMITED',
          'CYG': u'COVENTRY GROUP',
          'DCG': u'DECMIL GROUP LIMITED',
          'DGX': u'DIPLOMA GROUP LTD',
          'DSB': u'DELTA SBD LIMITED',
          'DTQ': u'DRILL TORQUE LTD',
          'EAL': u'E & A LIMITED',
          'EGL': u'ENVIRONMENTAL GROUP',
          'EGN': u'ENGENCO LIMITED',
          'EGY': u'ENERGY TECH LTD',
          'EHL': u'EMECO HOLDINGS',
          'EIM': u'EL CORPORATION LTD',
          'EMB': u'EMBELTON LIMITED',
          'EMM': u'ELECTROMETALS TECH.',
          'EOS': u'ELECTRO OPTIC SYS.',
          'EVZ': u'EVZ LIMITED',
          'FGE': u'FORGE GROUP LIMITED',
          'FGI': u'FLAT GLASS IND.',
          'FRR': u'FRR CORPORATION LTD',
          'GCS': u'GLOBAL CONSTRUCTION',
          'GGH': u'GLOBAL GOLD HLD LTD',
          'GLG': u'GERARD LIGHTING',
          'GNG': u'GR ENGINEERING LTD',
          'GRG': u'GRG INTERNATIONAL',
          'GWA': u'GWA GROUP LTD',
          'HDX': u'HUGHES DRILLING LTD',
          'HIL': u'HILLS HOLDINGS LTD',
          'HNG': u'HGL LIMITED',
          'HST': u'HASTIE GROUP LIMITED',
          'HTI': u'HYDROTECH INTER.',
          'HWE': u'HENRY WALKER ELTIN',
          'IDL': u'INDUSTREA LIMITED',
          'IFS': u'IFS CONSTRUCTION LTD',
          'ISL': u'INTELLIGENT SOLAR',
          'JVG': u'JV GLOBAL LIMITED',
          'KNH': u'KOON HOLDINGS',
          'KTL': u'KTL TECHNOLOGIES LTD',
          'LBL': u'LASERBOND LIMITED',
          'LCM': u'LOGICAMMS LIMITED',
          'LDW': u'LUDOWICI LIMITED',
          'LEI': u'LEIGHTON HOLDINGS',
          'LYL': u'LYCOPODIUM LIMITED',
          'MAH': u'MACMAHON HOLDINGS',
          'MBD': u'MARBLETREND GROUP',
          'MLD': u'MACA LIMITED',
          'MND': u'MONADELPHOUS GROUP',
          'MSI': u'MULTISTACK INTERNAT.',
          'MST': u'METAL STORM LIMITED',
          'MXI': u'MAXITRANS INDUSTRIES',
          'MYA': u'MY ATM HOLDINGS LTD',
          'MYE': u'MASTERMYNE GROUP LTD',
          'NOD': u'NOMAD BUILDING',
          'NWH': u'NRW HOLDINGS LIMITED',
          'OLH': u'OLDFIELDS HOLDINGS',
          'OTI': u'ORIENTAL TECHNO.',
          'PPX': u'PAPERLINX LIMITED',
          'PTB': u'PTB GROUP LIMITED',
          'QHL': u'QUICKSTEP HOLDINGS',
          'RCR': u'RCR TOMLINSON',
          'REH': u'REECE AUSTRALIA LTD.',
          'RFT': u'RECTIFIER TECHNOLOG',
          'RFX': u'REDFLOW LIMITED',
          'RIG': u'RONGTAI INT GRP LTD',
          'RQL': u'RESOURCE EQUIP LTD',
          'RWH': u'ROYAL WOLF HOLDINGS',
          'SAV': u'SAVCOR GROUP LIMITED',
          'SDM': u'SEDGMAN LIMITED',
          'SHR': u'(SHEARER (JOHN) HLDGS)',
          'SIT': u'SITE GROUP INT LTD',
          'SIV': u'SILVER CHEF LIMITED',
          'SKS': u'(STOKES (AUSTRALASIA))',
          'SLE': u'SINO-EXCEL ENERGY',
          'SND': u'SAUNDERS INTL LTD',
          'SRH': u'SAFEROADS HOLDINGS',
          'SSM': u'SERVICE STREAM',
          'SST': u'STEAMSHIPS TRADING',
          'STS': u'STRUCTURAL SYSTEMS',
          'SVW': u'SEVEN GROUP HOLDINGS',
          'SWK': u'SWICK MINING',
          'SWL': u'SEYMOUR WHYTE LTD',
          'SXE': u'STH CRS ELECT ENGNR',
          'SYP': u'STYLE LIMITED',
          'THO': u'THOMAS & COFFEY',
          'TZL': u'TZ LIMITED',
          'UGL': u'UGL LIMITED',
          'VGP': u'VERTICON GROUP LTD.',
          'VMG': u'VDM GROUP LIMITED',
          'VTX': u'VORTEX PIPES LTD',
          'WDS': u'WDS LIMITED',
          'WTP': u'WATPAC LIMITED',
          'XRF': u'XRF SCIENTIFIC',
          'ZGL': u'ZICOM GROUP LIMITED'},
 '2020': {'AEI': u'AERIS ENVIRONMENTAL',
          'AMB': u'AMBITION GROUP LTD',
          'ANQ': u'ANAECO LIMITED',
          'ARA': u'ARIADNE AUSTRALIA',
          'AZG': u'ALLMINE GROUP LTD',
          'BKM': u'BKM MANAGEMENT LTD',
          'BSA': u'BSA LIMITED',
          'BXB': u'BRAMBLES LIMITED',
          'CAB': u'CABCHARGE AUSTRALIA',
          'CBP': u'CARBON POLYMERS',
          'CCF': u'CARBON CONSCIOUS LTD',
          'CCP': u'CREDIT CORP GROUP',
          'CGR': u'CAREERS MULTILIST',
          'CLH': u'COLLECTION HOUSE',
          'CLQ': u'CLEAN TEQ HLDGS LTD',
          'CMG': u'CHANDLER MACLEOD LTD',
          'CMV': u'CMA CORPORATION LTD',
          'CND': u'CLARIUS GRP LTD',
          'COF': u'COFFEY INTERNATIONAL',
          'COZ': u'CO2 GROUP LIMITED',
          'CPB': u'CAMPBELL BROTHERS',
          'CRV': u'CORE SERV GRP',
          'DMX': u'DOLOMATRIX INTERNAT.',
          'DOW': u'DOWNER EDI LIMITED',
          'ECS': u'ECSI LIMITED',
          'ESI': u'ENV CLEAN TECH LTD',
          'EZA': u'EZEATM LIMITED',
          'GCG': u'GREENCAP LIMITED',
          'GNV': u'GREEN INVEST LTD',
          'HIT': u'HITECH GROUP AUST.',
          'HJB': u'HAMILTON JAMES BRUCE',
          'HMC': u'HYDROMET CORP. LTD',
          'HUM': u'HUMANIS GROUP LTD',
          'IVT': u'INVENTIS LIMITED',
          'MIN': u'MINERAL RESOURCES.',
          'MMS': u'MCMILLAN SHAKESPEARE',
          'NAM': u'NAMOI COTTON CO-OP',
          'NER': u'NEO RESOURCES LTD',
          'NFK': u'NORFOLK GROUP',
          'OPG': u'OPUS GROUP LTD',
          'OTC': u'OTOC LTD',
          'PEH': u'PACIFIC ENVIRONMENT',
          'PHK': u'PHOSLOCK WATER',
          'PMP': u'PMP LIMITED',
          'PRG': u'PROGRAMMED',
          'RCM': u'RECLAIM INDUSTRIES',
          'RDG': u'RES DEV GROUP LTD',
          'RUB': u'RUBICOR GROUP',
          'RUL': u'RUNGE LIMITED',
          'SAI': u'SAI GLOBAL LIMITED',
          'SEK': u'SEEK LIMITED',
          'SKE': u'SKILLED GROUP LTD',
          'SLM': u'SALMAT LIMITED',
          'SPT': u'SPOTLESS GROUP LTD',
          'STP': u'STERIHEALTH LIMITED',
          'TOX': u'TOX FREE SOLUTIONS',
          'TPI': u'TRANSPACIFIC INDUST.',
          'TSE': u'TRANSFIELD SERVICES',
          'TSN': u'TRANSACTION LTD',
          'TWO': u'TALENT2 INTERNATION',
          'WHG': u'WHK GROUP LIMITED',
          'WLL': u'WELLCOM GROUP LTD',
          'ZBI': u'BRAMBLES IND. PLC'},
 '2030': {'AIA': u'AUCKLAND INTERNATION',
          'AIO': u'ASCIANO LIMITED',
          'AIX': u'AUSTRALIAN INFRASTR.',
          'AIZ': u'AIR NEW ZEALAND',
          'AQZ': u'ALLIANCE AVIATION',
          'BCS': u'BRISCONNECTION TRUST',
          'CHR': u'CHALMERS LIMITED',
          'CLX': u'CTI LOGISTICS',
          'KSC': u'K & S CORPORATION',
          'LAU': u'LINDSAY AUSTRALIA',
          'MQA': u'MACQ ATLAS ROADS GRP',
          'MRM': u'MERMAID MARINE',
          'QAN': u'QANTAS AIRWAYS',
          'QRN': u'QR NATIONAL LIMITED',
          'QUB': u'QUBE LOGISTICS HLDG',
          'RCY': u'RIVERCITY MOTORWAY',
          'REX': u'REGIONAL EXPRESS',
          'RIS': u'RICHFIELD INTERNAT.',
          'SCC': u'SCOTT CORPORATION.',
          'SXR': u'SKYWEST AIRLINES LTD',
          'SYD': u'SYD AIRPORT',
          'TCL': u'TRANSURBAN GROUP',
          'TOL': u'TOLL HOLDINGS LTD',
          'TTI': u'TRAFFIC TECHNOLOGIES',
          'VAH': u'VIRGIN AUS HLDG LTD',
          'WNI': u'WAH NAM INT HLDG LTD'},
 '2510': {'ABV': u'ADV BRAKING TECH LTD',
          'ACE': u'ADVANCED ENGINE',
          'AIE': u'AUTODOM LIMITED',
          'BER': u'BERKLEE LIMITED',
          'DDT': u'DATADOT TECHNOLOGY',
          'FWD': u'FLEETWOOD CORP',
          'ION': u'ION LIMITED',
          'OEC': u'ORBITAL CORP LIMITED',
          'SFC': u'SCHAFFER CORP. LTD.',
          'SIX': u'SPRINTEX LTD',
          'SNL': u'SUPPLY NETWORK',
          'VMT': u'VMOTO LIMITED'},
 '2520': {'AKP': u'AUDIO PIXELS LTD',
          'APB': u'ARAFURA PEARLS HOLD.',
          'ATP': u'ATLAS SOUTHSEA PEARL',
          'BBG': u'BILLABONG',
          'FPA': u'FISHER & PAYKEL APP.',
          'GAP': u'GALE PACIFIC LIMITED',
          'GLB': u'GLOBE INTERNATIONAL',
          'GLE': u'GLG CORP LTD',
          'GPG': u'GUINNESS PEAT GROUP.',
          'GUD': u'G.U.D. HOLDINGS',
          'GZL': u'GAZAL CORPORATION',
          'ISK': u'ISLAND SKY AUSTRALIA',
          'KFG': u'KINGFORM HEALTH HOME',
          'KRS': u'KRESTA HOLDINGS',
          'MCP': u"(MCPHERSON'S LTD)",
          'MES': u'MESBON CHINA NYLON',
          'MHI': u'MERCHANT HOUSE',
          'PTO': u'PTO CONSOLIDATED LTD',
          'QTM': u'QUANTUM ENERGY.',
          'SHU': u'SHENHUA LTD',
          'TWD': u'TAMAWOOD LIMITED',
          'TWT': u'TWT GROUP LIMITED',
          'TYO': u'TREYO LEISURE',
          'UCW': u'UNDERCOVERWEAR LTD',
          'WAT': u'WATERCO LIMITED',
          'YHL': u'YANGHAO INT LTD'},
 '2530': {'AAD': u'ARDENT LEISURE GROUP',
          'ABQ': u'ALLIED BRANDS LTD',
          'AGI': u'AINSWORTH GAME TECH.',
          'AIG': u'AIRCRUISING AUST.',
          'AKG': u'ACADEMIES AUS GRP',
          'ALL': u'ARISTOCRAT LEISURE',
          'ATH': u'ATECH HOLDINGS',
          'CKF': u'COLLINS FOODS LTD',
          'CTD': u'CORP TRAVEL LIMITED',
          'CWN': u'CROWN LIMITED',
          'DMP': u'DOMINO PIZZA ENTERPR',
          'EBG': u'EUMUNDI GROUP LTD',
          'EBT': u'EBET LIMITED',
          'EGP': u'ECHO ENTERTAINMENT',
          'FLT': u'FLIGHT CENTRE',
          'GEM': u'G8 EDUCATION LIMITED',
          'IAW': u'INTEGRATED LEGAL',
          'IDP': u'INDOPAC HOLDINGS LTD',
          'IVC': u'INVOCARE LIMITED',
          'JET': u'JETSET TRAVELWORLD',
          'KME': u'KIP MCGRATH EDU.CNTR',
          'MAC': u'MACRO CORP. LIMITED',
          'NHH': u'NEWHAVEN HOTELS LTD',
          'NLG': u'NATIONAL LEISURE',
          'NVT': u'NAVITAS LIMITED',
          'OCE': u'OCEAN CAPITAL',
          'PPN': u'PLANET PLATINUM LTD',
          'RCT': u'REEF CASINO TRUST',
          'RDH': u'REDHILL EDUCATION',
          'RFG': u'RETAIL FOOD GROUP',
          'SGH': u'SLATER & GORDON',
          'SGU': u'SUCCESS RES GLOBAL',
          'SKC': u'SKY CITY ENTERTAIN.',
          'SSI': u'SINO STRATEGIC INTL',
          'TAH': u'TABCORP HOLDINGS LTD',
          'TAU': u'TRUSTEES AUST LTD',
          'TCO': u'TRANSMETRO CORP. LTD',
          'TTS': u'TATTS GROUP LTD',
          'VEL': u'VEALLS LIMITED',
          'VIA': u'VIAGOLD CAPITAL',
          'XXL': u'XIAOXIAO EDUCATION'},
 '2540': {'AAU': u'ADCORP AUSTRALIA',
          'ABN': u'ADEFFECTIVE LTD',
          'AHD': u'AMALGAMATED HOLDINGS',
          'APN': u'APN NEWS & MEDIA',
          'ASP': u'ASPERMONT LIMITED.',
          'BBL': u'BRISBANE BRONCOS',
          'BYI': u'BEYOND INTERNATIONAL',
          'CMJ': u'CONSOLIDATED MEDIA.',
          'COJ': u'COMMSTRAT LIMITED',
          'DIG': u'DIGITAL PERF GRP LTD',
          'FXJ': u'FAIRFAX MEDIA LTD',
          'HYO': u'HYRO LIMITED',
          'MEG': u'MCM ENTERTAINMENT GR',
          'MOT': u'MOTOPIA LTD',
          'MRN': u'MACQUARIE RADIO',
          'MUI': u'MUI CORP LIMITED',
          'NWS': u'NEWS CORP',
          'ONL': u'ONE NORTH ENT LTD',
          'PGA': u'PHOTON GROUP LTD',
          'PNW': u'PACIFIC STAR NETWORK',
          'PRT': u'PRIME MEDIA GRP LTD',
          'QXQ': u'Q LIMITED',
          'REA': u'REA GROUP',
          'RMA': u'REELTIME MEDIA',
          'SGN': u'STW COMMUNICATIONS',
          'SKT': u'SKY NETWORK',
          'SWM': u'SEVEN WEST MEDIA LTD',
          'SXL': u'STHN CROSS MEDIA',
          'TEN': u'TEN NETWORK HOLDINGS',
          'VRL': u'VILLAGE ROADSHOW LTD',
          'WAG': u'WAG LIMITED',
          'WWG': u'WORLD WIDE ENT GRP'},
 '2550': {'AHE': u'AUTOMOTIVE HOLDINGS',
          'AMA': u'AMA GROUP LIMITED',
          'APE': u'A.P. EAGERS LIMITED',
          'ARP': u'ARB CORPORATION',
          'BIC': u'BIRON APPAREL LTD',
          'BRG': u'BREVILLE GROUP LTD',
          'BSI': u'BEYOND SPORTSWEAR',
          'CCV': u'CASH CONVERTERS',
          'CNC': u'CONS CAP INVEST LTD',
          'CTY': u'COUNTRY ROAD LIMITED',
          'DJS': u'DAVID JONES LIMITED',
          'DLC': u'DELECTA LIMITED',
          'FAN': u'FANTASTIC HOLDINGS',
          'FUN': u'FUNTASTIC LIMITED',
          'HII': u'HIRE INTELLIGENCE',
          'HVN': u'HARVEY NORMAN',
          'JBH': u'JB HI-FI LIMITED',
          'JIN': u'JUMBO INTERACTIVE',
          'JYC': u'JOYCE CORPORATION',
          'KMD': u'KATHMANDU HOLD LTD',
          'MLC': u'MOTHERCARE AUS LTD',
          'MYR': u'MYER HOLDINGS LTD',
          'MZU': u'MAZU ALLIANCE LTD',
          'NBL': u'NONI B LIMITED',
          'NCK': u'NICK SCALI LIMITED',
          'ORL': u'OROTONGROUP LIMITED',
          'OTH': u'ONTHEHOUSE LTD',
          'PBG': u'PACIFIC BRANDS',
          'PMV': u'PREMIER INVESTMENTS',
          'QFX': u'QUICKFLIX LIMITED',
          'RCG': u'RCG CORPORATION LTD',
          'RHL': u'RURALCO HOLDINGS',
          'SFH': u'SPECIALTY FASHION',
          'SRA': u'STRATHFIELD GROUP',
          'SUL': u'SUPER RET REP LTD',
          'TGA': u'THORN GROUP LIMITED',
          'TME': u'TRADE ME GROUP',
          'TRS': u'THE REJECT SHOP',
          'VTG': u'VITA GROUP LTD',
          'WEB': u'WEBJET LIMITED',
          'WHS': u'WAREHOUSE GROUP',
          'WTF': u'WOTIF.COM HOLDINGS'},
 '3010': {'HEA': u'HEALTH CORPORATION',
          'MTS': u'METCASH LIMITED',
          'RLA': u'REDISLAND AUSTRALIA',
          'WES': u'WESFARMERS LIMITED',
          'WOW': u'WOOLWORTHS LIMITED'},
 '3020': {'AAC': u'AUSTRALIAN AGRICULT.',
          'AAQ': u'AAQ HOLDINGS LTD',
          'AVG': u'AUST VINTAGE LTD',
          'BGA': u'BEGA CHEESE LTD',
          'BNV': u'BRAND NEW VINTAGE',
          'BUG': u'BUDERIM GINGER',
          'CCL': u'COCA-COLA AMATIL',
          'CJG': u'CHINA JXY GROUP LTD',
          'CSS': u'CLEAN SEAS TUNA',
          'CVS': u'CERVANTES CORP LTD',
          'DMY': u'DROMANA ESTATE',
          'ELD': u'ELDERS LIMITED',
          'FFI': u'F.F.I. HOLDINGS',
          'FLR': u'FRANKLAND RIVER',
          'FNP': u'FREEDOM FOOD LTD',
          'FRM': u'FARM PRIDE FOODS',
          'FWA': u'FARMWORKS AUST',
          'GFF': u'GOODMAN FIELDER.',
          'GNC': u'GRAINCORP LIMITED',
          'GRB': u'GAGE ROADS BREWING',
          'GSF': u'GSF CORPORATION LTD',
          'LWB': u'LITTLE WORLD BEV.',
          'MTI': u'MONTEC INTERNATIONAL',
          'OZB': u'OZ BREWING LIMITED',
          'PAG': u'PRIMEAG AUSTRALIA',
          'PFL': u'PATTIES FOODS LTD',
          'PHW': u'PRINCE HILL WINES',
          'RGP': u'REFRESH GROUP',
          'RIC': u'RIDLEY CORPORATION',
          'SDT': u'SHANDONG TIANYE AUS',
          'SHV': u'SELECT HARVESTS',
          'SOI': u'SOILSUB TECHNOLOGIES',
          'TAN': u'TANDOU LIMITED',
          'TGR': u'TASSAL GROUP LIMITED',
          'TWE': u'TREASURY WINE ESTATE',
          'TWH': u'TW HOLDINGS LTD',
          'VTA': u'VITERRA INC',
          'WBA': u'WEBSTER LTD',
          'WCB': u'WARRNAMBOOL CHEESE'},
 '3030': {'BKL': u'BLACKMORES LIMITED',
          'ECQ': u'ECO QUEST',
          'HZL': u'HZ LIM LTD'},
 '3510': {'ACG': u'ATCOR MEDICAL',
          'ADO': u'ANTEO DIAGNOSTICS',
          'AHZ': u'ALLIED HEALTH LTD',
          'AJJ': u'ASIA LIVER TRANS LTD',
          'ALT': u'ANALYTICA LIMITED',
          'AMT': u'ADV SURG DSGN & MNFT',
          'ANN': u'ANSELL LIMITED',
          'API': u'AUSTRALIAN PHARM.',
          'ATW': u'ATW HOLDINGS LTD',
          'BRC': u'BRAIN RESOURCE LTD',
          'CAJ': u'CAPITOL HEALTH',
          'CBB': u'CORDLIFE LIMITED',
          'CGS': u'COGSTATE LTD',
          'CLV': u'CLOVER CORPORATION',
          'CMP': u'COMPUMEDICS LIMITED',
          'COH': u'COCHLEAR LIMITED',
          'CXD': u'CATHRX LTD',
          'CYC': u'CYCLOPHARM LIMITED',
          'ELX': u'ELLEX MEDICAL LASERS',
          'EPL': u'EYECARE PARTNERS LTD',
          'FPH': u'FISHER & PAYKEL H.',
          'GID': u'GI DYNAMICS, INC',
          'GLH': u'GLOBAL HEALTH LTD',
          'GXL': u'GREENCROSS LIMITED',
          'HIN': u'HEARTWARE INT INC',
          'ICS': u'ICSGLOBAL LIMITED',
          'IMI': u'IM MEDICAL LTD',
          'IPD': u'IMPEDIMED LIMITED',
          'ISN': u'ISONEA LIMITED',
          'ITD': u'ITL LIMITED',
          'KKT': u'KONEKT LIMITED',
          'LBT': u'LBT INNOVATIONS',
          'LER': u'LEAF ENERGY LIMITED',
          'MDG': u'MEDTECH GLOBAL',
          'MDV': u'MEDIVAC LIMITED',
          'MGZ': u'MEDIGARD LIMITED',
          'MLA': u'MEDICAL AUS LIMITED',
          'NAN': u'NANOSONICS LIMITED',
          'OIL': u'OPTISCAN IMAGING',
          'OMI': u'OMI HOLDINGS LIMITED',
          'ONT': u'1300 SMILES LIMITED',
          'OSP': u'OSPREY MED INC',
          'PGC': u'PARAGON CARE LIMITED',
          'PHG': u'PULSE HEALTH LIMITED',
          'PHL': u'PEARL HEALTHCARE',
          'PLD': u'PLD CORPORATION LTD',
          'PME': u'PRO MEDICUS LIMITED',
          'PRY': u'PRIMARY HEALTH CARE',
          'RHC': u'RAMSAY HEALTH CARE',
          'RHT': u'RESONANCE HEALTH',
          'RMD': u'RESMED INC',
          'RVA': u'REVA MEDICAL, INC',
          'SBN': u'SUN BIOMEDICAL LTD',
          'SDI': u'SDI LIMITED',
          'SFP': u'SAFETY MEDICAL',
          'SHC': u'SUNSHINE HEART, INC.',
          'SHL': u'SONIC HEALTHCARE',
          'SIP': u'SIGMA PHARMACEUTICAL',
          'SOM': u'SOMNOMED LIMITED',
          'TLZ': u'SIM.TLZ',
          'TPP': u'TEMPO AUSTRALIA',
          'UBI': u'UNIVERSAL BIOSENSORS',
          'UCM': u'USCOM LIMITED',
          'UNS': u'UNILIFE CORPORATION',
          'VEI': u'VISION EYE INSTITUTE'},
 '3520': {'ACL': u'ALCHEMIA LIMITED',
          'ACR': u'ACRUX LIMITED',
          'ACU': u'ACUVAX LIMITED',
          'ACW': u'ACTINOGEN LIMITED',
          'AGX': u'AGENIX LIMITED',
          'ANP': u'ANTISENSE THERAPEUT.',
          'AVH': u'AVITA MEDICAL LTD',
          'AVX': u'AVEXA LIMITED',
          'BDM': u'BIODIEM LIMITED',
          'BIT': u'BIOTRON LIMITED',
          'BLT': u'BENITEC BIOPHARMA',
          'BNC': u'BIONICHE LIFE INC',
          'BNE': u'BONE MEDICAL LIMITED',
          'BNO': u'BIONOMICS LIMITED',
          'BPH': u'BPH ENERGY LTD',
          'BPO': u'BIOPROSPECT LIMITED',
          'BTA': u'BIOTA HOLDINGS',
          'BXN': u'BIOXYNE LTD',
          'CBZ': u'CBIO LIMITED',
          'CDY': u'CELLMID LIMITED',
          'CGP': u'CONSEGNA GROUP LTD',
          'CIR': u'CIRCADIAN TECH',
          'CSL': u'CSL LIMITED',
          'CTE': u'CRYOSITE LIMITED',
          'CUV': u'CLINUVEL PHARMACEUT.',
          'CZD': u'CALZADA LIMITED',
          'EMS': u'EASTLAND MEDICAL',
          'GBI': u'GENERA BIOSYSTEMS',
          'GEN': u'GENESIS RESEARCH',
          'GIA': u'GIACONDA LIMITED',
          'GTG': u'GENETIC TECHNOLOGIES',
          'HCT': u'HOLISTA COLLTECH LTD',
          'HTX': u'HEALTHLINX LIMITED',
          'IDT': u'IDT AUSTRALIA LTD',
          'IMC': u'IMMURON LIMITED',
          'IMU': u'IMUGENE LIMITED',
          'LCT': u'LIVING CELL TECH.',
          'LMB': u'LAMBOO RESOURCES',
          'MSB': u'MESOBLAST LIMITED',
          'MVP': u'MEDICAL DEVELOPMENTS',
          'MYX': u'MAYNE PHARMA LTD',
          'NDL': u'NEURODISCOVERY',
          'NEU': u'NEUREN PHARMACEUT.',
          'NLS': u'NARHEX LIFE SCIENCES',
          'NRT': u'NOVOGEN LIMITED',
          'NSP': u'NUSEP HOLDINGS LTD',
          'OBJ': u'OBJ LIMITED',
          'PAA': u'PHARMAUST LIMITED',
          'PAB': u'PATRYS LIMITED',
          'PBP': u'PROBIOTEC LIMITED',
          'PBT': u'PRANA BIOTECHNOLOGY',
          'PGL': u'PROGEN PHARMACEUTIC',
          'PNO': u'PHARMANET GROUP',
          'POH': u'PHOSPHAGENICS LTD.',
          'PRR': u'PRIMA BIOMED LTD',
          'PVA': u'PSIVIDA CORP',
          'PXS': u'PHARMAXIS LTD',
          'PYC': u'PHYLOGICA LIMITED',
          'QRX': u'QRXPHARMA LTD',
          'SIE': u'SCIGEN LIMITED',
          'SLA': u'SOLAGRAN LIMITED',
          'SPL': u'STARPHARMA HOLDINGS',
          'SRX': u'SIRTEX MEDICAL',
          'STI': u'STIRLING PRODUCTS',
          'TDX': u'TYRIAN DIAGNOSTICS',
          'TEO': u'TELESSO TECH LTD',
          'TIS': u'TISSUE THERAPIES',
          'VHL': u'VIRAX HOLDINGS',
          'VLA': u'VIRALYTICS LIMITED',
          'VSC': u'VITA LIFE SCIENCES.'},
 '4010': {'ANZ': u'ANZ BANKING GRP LTD',
          'BEN': u'BENDIGO AND ADELAIDE',
          'BOQ': u'BANK OF QUEENSLAND.',
          'CBA': u'COMMONWEALTH BANK.',
          'FFF': u'FIRSTFOLIO LIMITED',
          'GMY': u'GOLDFIELDS MONEY',
          'HOM': u'HOMELOANS LIMITED',
          'MOC': u'MORTGAGE CHOICE LTD',
          'MYS': u'MYSTATE LIMITED',
          'NAB': u'NATIONAL AUST. BANK',
          'RHG': u'RHG LIMITED',
          'WBB': u'WIDE BAY AUST LTD',
          'WBC': u'WESTPAC BANKING CORP'},
 '4020': {'AAO': u'ADEPT SOLUTIONS LTD',
          'AAY': u'AACL HOLDINGS LTD',
          'ACK': u'AUSTOCK GROUP LTD',
          'AEF': u'AUSTRALIAN ETHICAL',
          'AFA': u'ASF GROUP LIMITED',
          'AFI': u'AUSTRALIAN FOUNDAT.',
          'AFV': u'AURORA FUNDS LIMITED',
          'AGF': u'AMP CAPITAL CHINA',
          'AIB': u'AURORA GLB TRUST',
          'AIK': u'ARMIDALE INVEST CORP',
          'AIQ': u'ALTERNATIVE INVEST',
          'AKF': u'ASK FUNDING LIMITED',
          'AKW': u'ARTURUS CAPITAL LTD',
          'AKX': u'AMCBF FOUR',
          'AKY': u'AMCBF FIVE',
          'ALF': u'AUSTRALIAN LEADERS',
          'ALR': u'ABERDEEN LEADERS',
          'AMH': u'AMCIL LIMITED',
          'APD': u'APN PROPERTY GROUP',
          'APP': u'APA FINANCIAL',
          'AQF': u'AUS GOV INDEX FUND',
          'ARG': u'ARGO INVESTMENTS',
          'ASW': u'ADVANCED SHARE LTD',
          'ASX': u'ASX LIMITED',
          'AUF': u'ASIAN MASTERS FUND',
          'AUI': u'AUSTRALIAN UNITED IN',
          'AYI': u'A1 INVEST & RES LTD',
          'BEL': u'BENTLEY CAPITAL LTD',
          'BFG': u'BELL FINANCIAL GROUP',
          'BKI': u'BKI INVESTMENT LTD',
          'BLA': u'BLUE SKY LIMITED',
          'BSN': u'BISAN LIMITED',
          'BTC': u'BIOTECH CAPITAL',
          'BTT': u'BT INVESTMENT MNGMNT',
          'CAF': u'CENTREPOINT ALLIANCE',
          'CAM': u'CLIME CAPITAL',
          'CDM': u'CADENCE CAPITAL',
          'CFY': u'CFT ENERGY LTD',
          'CGF': u'CHALLENGER LIMITED',
          'CHF': u'CHARTER PACIFIC',
          'CHP': u'CHAPMANS LIMITED',
          'CIN': u'CARLTON INVESTMENTS',
          'CIW': u'CLIME INVESTMENT',
          'CNG': u'COLONIAL HOLDING LTD',
          'CNI': u'CENTURIA CAPITAL',
          'COT': u'CONTINUATION INVEST',
          'CSJ': u'CS GP100 AUST TRUST',
          'CSU': u'CS100 EMRG MKT INFRA',
          'CTN': u'CONTANGO MICROCAP',
          'CUP': u'COUNTPLUS LIMITED',
          'CVC': u'CVC LIMITED',
          'CYA': u'CENTURY AUSTRALIA',
          'DJW': u'DJERRIWARRH',
          'DUI': u'DIVERSIFIED UNITED',
          'DVA': u'DIVERSA LIMITED',
          'DXR': u'DEXUS RENTS TRUST',
          'ELI': u'EMERGING LEADERS INV',
          'EQF': u'EQUITIES & FREEHOLDS',
          'EQT': u'EQUITY TRUSTEES',
          'EXA': u'EXCELA LIMITED',
          'EZL': u'EUROZ LIMITED',
          'FGF': u'FIRST GROWTH FUNDS',
          'FPS': u'FIDUCIAN PORTFOLIO',
          'FSA': u'FSA GROUP LIMITED',
          'FXL': u'FLEXIGROUP LIMITED',
          'GBA': u'GRANDBRIDGE LIMITED',
          'GFL': u'GLOBAL MASTERS FUND',
          'GMI': u'GLOBAL MINING',
          'GOL': u'ETFS METALS.',
          'GOW': u'GOWING BROS. LIMITED',
          'GRF': u'GLOBAL RESOURCE',
          'GRP': u'GRP CORP LIMITED',
          'HFA': u'HFA HOLDINGS LIMITED',
          'HGG': u'HENDERSON GROUP',
          'HHL': u'HUNTER HALL INTER.',
          'HHV': u'HUNTER HALL GLOBAL',
          'HHY': u'HASTINGS HIGH YIELD',
          'HIP': u'HYPERION FLAGSHIP',
          'HLS': u'HILLCREST LITIGAT.',
          'IBC': u'IRONBARK CAPITAL LTD',
          'IFL': u'IOOF HOLDINGS LTD',
          'IMF': u'(IMF (AUSTRALIA) LTD)',
          'INQ': u'INVESTORFIRST LTD',
          'IPA': u'INDIGO PROP AUS LTD',
          'IPC': u'IMPERIAL PACIFIC LTD',
          'IPE': u'ING PRIVATE EQUITY',
          'KAM': u'K2 ASSET MGMT HLDGS',
          'KAT': u'KATANA CAPITAL',
          'KBC': u'KEYBRIDGE CAPITAL',
          'LCE': u'LONDON CITY EQU. LTD',
          'LRF': u'LINQ RESOURCES FUND',
          'MCH': u'MURCHISON HOLDINGS',
          'MCX': u'MARINER CORP LTD',
          'MEF': u'MERRICKS CAPITAL LTD',
          'MFF': u'MAGELLAN FLAGSHIP',
          'MFG': u'MAGELLAN FIN GRP LTD',
          'MIR': u'MIRRABOOKA INVEST.',
          'MLT': u'MILTON CORPORATION',
          'MNY': u'MONEY3 CORPORATION',
          'MQG': u'MACQUARIE GROUP LTD',
          'MRJ': u'MERIDIEN RES LTD',
          'MUT': u'MULTI CHANNEL',
          'MVT': u'MERCANTILE INVEST',
          'NSX': u'NSX LIMITED',
          'OCP': u'OCEANIA CAPITAL LTD',
          'OEQ': u'ORION EQUITIES',
          'ONC': u'ONCARD INTERNATIONAL',
          'ORC': u'ORCHID CAPITAL',
          'OZG': u'OZGROWTH LIMITED',
          'PET': u'PETERS MACGREGOR INV',
          'PFG': u'PRIME FINANCIAL',
          'PHA': u'PUBLIC HOLDINGS',
          'PLB': u'PLAN B GROUP HLD',
          'PMC': u'PLATINUM CAPITAL LTD',
          'PPT': u'PERPETUAL LIMITED',
          'PRV': u'PREMIUM INVESTORS',
          'PTM': u'PLATINUM ASSET',
          'QSS': u'QUESTUS LIMITED',
          'QST': u'QUEST INVESTMENTS',
          'RAF': u'RAFFLES CAPITAL LTD',
          'RKS': u'RKS CONS LTD',
          'SFN': u'STANFIELD FUNDS LTD',
          'SFW': u'SFG AUSTRALIA LTD',
          'SGI': u'SIGNATURE CAP LTD',
          'SOL': u'(SOUL PATTINSON (W.H))',
          'SOR': u'STRATEGIC ELEMENTS',
          'SPD': u'STRATEGIC POOLED',
          'SVS': u'SUNVEST CORPORATION',
          'TAG': u'TAG PACIFIC LIMITED',
          'TCN': u'TECHNICHE LIMITED.',
          'TDI': u'TIDEWATER INVESTMENT',
          'TFS': u'TRANZACT FIN.SERVICE',
          'TGG': u'TEMPLETON GLOBAL',
          'TJN': u'TROJAN EQUITY',
          'TPA': u'TRANSPACIFIC SPS',
          'TRG': u'TREASURY GROUP',
          'TRU': u'THE TRUST COMP LTD',
          'TSM': u'THINKSMART LIMITED',
          'VIE': u'VIENTO GROUP LIMITED',
          'VIL': u'VERUS INVESTMENTS',
          'WAA': u'WAM ACTIVE LIMITED',
          'WAM': u'WAM CAPITAL LIMITED',
          'WAX': u'WAM RESEARCH LTD',
          'WHF': u'WHITEFIELD LTD',
          'WIC': u'WESTOZ INV LTD',
          'WIG': u'WILSON HTM INVEST.',
          'YBR': u'YELLOW BRICK ROAD',
          'ZHE': u'ZHENGHE GLOB CAP LTD'},
 '4030': {'AMP': u'AMP LIMITED',
          'AUB': u'AUSTBROKERS HOLDINGS',
          'CIX': u'CALLIDEN GROUP',
          'CVW': u'CLEARVIEW WEALTH LTD',
          'IAG': u'INSURANCE AUSTRALIA',
          'NHF': u'NIB HOLDINGS LIMITED',
          'QBE': u'QBE INSURANCE GROUP',
          'SBK': u'SUNCORP-METWAY .',
          'SUN': u'SUNCORP GROUP LTD',
          'TWR': u'TOWER LIMITED'},
 '4040': {'AAK': u'AUSTRALIA CHINA HOLD',
          'AAZ': u'AUSTRALAND ASSETS',
          'ABP': u'ABACUS PROPERTY GRP.',
          'AEU': u'AUSTRALIAN EDUCATION',
          'AEZ': u'APN EUROPEAN RETAIL',
          'AGJ': u'AGRICULTURAL LAND',
          'AHC': u'AHC LIMITED',
          'AJA': u'ASTRO JAP PROP GROUP',
          'AJO': u'ARMSTRONG JONES OFF.',
          'ALZ': u'AUSTRALAND PROPERTY',
          'APZ': u'ASPEN GROUP',
          'ARJ': u'(ARK FUND LTD (THE))',
          'AUP': u'AURORA PROPERTY',
          'AVJ': u'AVJENNINGS LIMITED',
          'AXI': u'AXIOM PROPERTIES',
          'AZF': u'AUS SOCIAL INFR FUND',
          'BAO': u'BROOKFIELD AUST OPP',
          'BEC': u'BECTON PROPERTY GRP.',
          'BPA': u'BROOKFIELD PRIME',
          'BWF': u'BLACKWALL PROPERTY',
          'BWP': u'BWP TRUST',
          'CDI': u'CHALLENGER DIV.PRO.',
          'CDL': u'CANADA LAND LIMITED',
          'CDP': u'CARINDALE PROPERTY',
          'CER': u'CENTRO RETAIL GROUP',
          'CFX': u'CFS RETAIL TRUST GRP',
          'CHC': u'CHARTER HALL GROUP',
          'CJT': u'CVC PROPERTY FUND',
          'CKP': u'CHEVIOT KIRRIBILLI',
          'CMW': u'CROMWELL PROP',
          'CNB': u'CIC AUSTRALIA LTD',
          'CNP': u'CNPR GRP',
          'CNR': u'COONAWARRA AUSTRALIA',
          'CPA': u'COMMONWEALTH PROP',
          'CPK': u'CP1 LIMITED',
          'CQR': u'CHARTER HALL RETAIL',
          'CRF': u'CENTRO RETAIL AUST',
          'CUI': u'CENTIUM ELECTRIC LTD',
          'CWP': u'CEDAR WOODS PROP.',
          'DDF': u'DEUTSCHE DIVERSIFIED',
          'DGH': u'DESANE GROUP HLDINGS',
          'DIT': u'DEUTSCHE INDUSTRIAL',
          'DOT': u'DEUTSCHE OFFICE',
          'DVN': u'DEVINE LIMITED',
          'DXS': u'DEXUS PROPERTY GROUP',
          'EGH': u'EUREKA GROUP LTD',
          'FKP': u'FKP PROPERTY GROUP',
          'FLK': u'FOLKESTONE LIMITED',
          'FPG': u'FOREST PLACE GROUP',
          'FRI': u'FINBAR GROUP LIMITED',
          'GHC': u'GEN HEALTHCARE REIT',
          'GJT': u'GALILEO JAPAN TRUST',
          'GMG': u'GOODMAN GROUP',
          'GOZ': u'GROWTHPOINT PROPERTY',
          'GPT': u'GPT GROUP',
          'HGL': u'HUDSON INVESTMENT',
          'IEF': u'IEF REAL ESTATE ENT',
          'IEQ': u'INTERNATIONAL EQUITI',
          'INA': u'INGENIA GROUP',
          'IOF': u'INVESTA OFFICE FUND',
          'LEP': u'ALE PROPERTY GROUP',
          'LIC': u'LIFESTYLE COMMUNIT.',
          'LLC': u'LEND LEASE GROUP',
          'LMW': u'LANDMARK WHITE LTD',
          'MGI': u'MACQUARIE GOODMAN',
          'MGM': u'MACQUARIE GOOD. MGT.',
          'MGR': u'MIRVAC GROUP',
          'MIX': u'MIRVAC INDUSTRIAL',
          'MPS': u'MACARTHURCOOK PROP.',
          'MTD': u'METROLAND AUSTRALIA',
          'MUE': u'MULTIPLEX EUROPEAN',
          'MXU': u'MULTIPLEX SITES',
          'PAY': u'PAYCE CONSOLIDATED',
          'PBD': u'PORT BOUVARD LIMITED',
          'PHI': u'PHILEO AUSTRALIA',
          'PPC': u'PEET LIMITED',
          'PPK': u'PPK GROUP LIMITED',
          'PRP': u'PRIME CREDIT PROP.',
          'PTN': u'PRIME RETIREMENT',
          'PXT': u'P-REIT',
          'RCU': u'REAL ESTATE CAPITAL',
          'RLG': u'RCL GROUP',
          'RNC': u'RUN CORP LIMITED',
          'RNY': u'RNY PROPERTY TRUST',
          'RPG': u'RAPTIS GROUP LIMITED',
          'SAP': u'SABINA CORPORATION',
          'SDG': u'SUNLAND GROUP LTD',
          'SGP': u'STOCKLAND',
          'SRV': u'SERVCORP LIMITED',
          'SSL': u'SIETEL LIMITED',
          'SVC': u'SVC GROUP LIMITED',
          'TCQ': u'TRINITY GROUP',
          'TGP': u'TRAFALGAR CORPORATE',
          'THG': u'THAKRAL HOLDINGS GRP',
          'TSO': u'TISHMAN SPEYER',
          'TYS': u'TEYS LIMITED',
          'UOS': u'UNITED OVERSEAS AUST',
          'VCL': u'VICULUS LIMITED',
          'VES': u'VESTURE LIMITED',
          'VLW': u'VILLA WORLD LTD.',
          'WDC': u'WESTFIELD GROUP',
          'WFA': u'WESTFIELD AMERICA',
          'WFT': u'WESTFIELD TRUST',
          'WRT': u'WESTFIELD RETAIL TST',
          'WSF': u'WESTFIELD HOLDINGS',
          'WWM': u'WENTWORTH HLDGS LTD'},
 '4510': {'AAS': u'ASIAN PACIFIC',
          'ADA': u'ADACEL TECHNOLOGIES',
          'ALU': u'ALTIUM LIMITED',
          'ASZ': u'ASG GROUP LIMITED',
          'AYG': u'ANITTEL GROUP LTD',
          'BHG': u'BEAUTY HEALTH LTD',
          'BPG': u'BYTE POWER GROUP',
          'BVA': u'BRAVURA SOLUTIONS',
          'CBK': u'CB AUST LTD',
          'CCK': u'CCK FINANCIAL',
          'CGO': u'CPT GLOBAL LIMITED',
          'COM': u'COMOPS LIMITED',
          'COO': u'CORUM GROUP LIMITED',
          'CPU': u'COMPUTERSHARE LTD',
          'CRZ': u'CARSALES.COM LTD',
          'CSV': u'CSG LIMITED',
          'CUS': u'CUSTOMERS LIMITED',
          'CYO': u'CLARITY OSS LTD',
          'DSQ': u'DSQ HOLDINGS LIMITED',
          'DTL': u'DATA#3 LIMITED',
          'DWS': u'DWS LTD',
          'EOL': u'ENERGY ONE LIMITED',
          'EPD': u'EMPIRED LTD',
          'EPY': u'E-PAY ASIA LIMITED',
          'ESN': u'ENTELLECT LIMITED',
          'ESV': u'ESERVGLOBAL LIMITED',
          'FAC': u'FACILITATE DIGITAL',
          'GBT': u'GBST HOLDINGS..',
          'GCN': u'GOCONNECT LIMITED',
          'HSN': u'HANSEN TECHNOLOGIES',
          'IAT': u'IATIA LIMITED',
          'IDE': u'IDEAS INTERNATIONAL',
          'IFM': u'INFOMEDIA LTD',
          'IPP': u'IPROPERTY GROUP LTD',
          'IPR': u'IPERNICA LIMITED',
          'IRE': u'IRESS LIMITED',
          'IRI': u'INTEGRATED RESEARCH',
          'ISS': u'ISS GROUP LIMITED',
          'IUL': u'IMAGINE UN LIMITED',
          'JMB': u'JUMBUCK ENTERTAINMNT',
          'LRG': u'LONGREACH GROUP.',
          'MBE': u'MOBILE EMBRACE LTD',
          'MLB': u'MELBOURNE IT LIMITED',
          'MMZ': u'MOOTER MEDIA LIMITED',
          'MNW': u'MINT WIRELESS',
          'MWR': u'MGM WIRELESS LIMITED',
          'MWS': u'MDS FINANCIAL GRP',
          'NUW': u'NUWORLD SOLUTIONS',
          'OCL': u'OBJECTIVE CORP',
          'OKN': u'OAKTON LIMITED',
          'ONQ': u'ON Q GROUP LIMITED',
          'PPS': u'PRAEMIUM LIMITED',
          'PRO': u'PROPHECY INTERNATION',
          'PSY': u'PANORAMA SYNERGY LTD',
          'QIL': u'(QUOIN (INT) LIMITED.)',
          'QNA': u'QANDA TECH LTD',
          'RDF': u'REDFLEX HOLDINGS',
          'RFL': u'RUBIK FINANCIAL LTD.',
          'RKN': u'RECKON LIMITED',
          'RXP': u'RXP SERVICES LTD',
          'SEN': u'SENETAS CORPORATION',
          'SIU': u'SIRIUS CORP LTD',
          'SMX': u'SMS MANAGEMENT.',
          'SNR': u'SYNERGY PLUS LIMITED',
          'SOF': u'SOFCOM LIMITED',
          'STE': u'STRATATEL LIMITED',
          'TNE': u'TECHNOLOGY ONE',
          'TQH': u'3Q HOLDINGS LIMITED',
          'TTV': u'TWO WAY LIMITED',
          'UXC': u'UXC LIMITED',
          'VIP': u'VOLTAGE IP LIMITED',
          'WFM': u'WEBFIRM GROUP LTD',
          'WNS': u'WORLD.NET SERVICES',
          'WSE': u'W STRANGER MINING',
          'ZMG': u'ZINGMOBILE GROUP LTD'},
 '4520': {'AAT': u'AAT CORPORATION LTD',
          'AMO': u'AMBERTECH LIMITED',
          'ARR': u'ARASOR INTERNATIONAL',
          'AZV': u'AZURE HEALTHCARE LTD',
          'BCT': u'BLUECHIIP LIMITED',
          'CDA': u'CODAN LIMITED',
          'CLS': u'CL ASSET HOLDINGS',
          'CLT': u'CELLNET GROUP',
          'CPS': u'COMPUTRONICS HOLD.',
          'CPZ': u'CAR PARK TECH LTD',
          'DDR': u'DICKER DATA LIMITED',
          'DGI': u'DIGISLIDE HOLDINGS',
          'EHG': u'ELLECT HOLDINGS',
          'ICP': u'ICASH PAYMENT SYSTEM',
          'INT': u'INTERMOCO LIMITED',
          'LGD': u'LEGEND CORPORATION',
          'LMC': u'LEMARNE CORPORATION',
          'MBO': u'MOBILARM LIMITED',
          'MIK': u'MIKOH CORPORATION',
          'MOV': u'MOV CORPORATION LTD',
          'MSP': u'MAXSEC GROUP LTD',
          'NTC': u'NETCOMM WIRELESS',
          'OHL': u'OMNITECH HOLDINGS',
          'PIE': u'PIENETWORKS LIMITED',
          'QTG': u'Q TECHNOLOGY GRP LTD',
          'SCD': u'SCANTECH LIMITED',
          'SMA': u'SMARTTRANS HOLDINGS',
          'SMN': u'STRUCTURAL MONITOR.',
          'TNC': u'TRANSOL CORPORATION',
          'TTA': u'TTA HOLDINGS LTD',
          'ULT': u'ULTRAPAY LIMITED',
          'WRR': u'WORLD REACH LTD',
          'XTE': u'XTEK LIMITED.'},
 '4530': {'BLG': u'BLUGLASS LIMITED',
          'DYE': u'DYESOL LIMITED',
          'SLX': u'SILEX SYSTEMS'},
 '5010': {'AMM': u'AMCOM TELECOMM.',
          'BGL': u'BIGAIR GROUP LIMITED',
          'BRO': u'BROAD INVESTMENTS',
          'CAG': u'CAPE RANGE LIMITED',
          'CNU': u'CHORUS LIMITED',
          'EFT': u'EFTEL LIMITED',
          'FRE': u'FRESHTEL HOLDINGS',
          'HTA': u'HUTCHISON',
          'IIN': u'IINET LIMITED',
          'MAQ': u'MACQUARIE TELECOM GP',
          'MKB': u'MOKO.MOBI LIMITED',
          'MNF': u'MY NET FONE LIMITED',
          'MNZ': u'MNET GROUP LIMITED.',
          'MTU': u'M2 TELECOMMUNICATION',
          'NBS': u'NEXBIS LIMITED',
          'NWT': u'NEWSAT LIMITED',
          'NXT': u'NEXTDC LIMITED',
          'QUE': u'QUESTE COMMUNICATION',
          'REF': u'REVERSE CORP LIMITED',
          'SGT': u'SINGAPORE TELECOMM.',
          'TEL': u'TELECOM CORPORATION',
          'TLS': u'TELSTRA CORPORATION.',
          'TPC': u'TEL.PACIFIC LIMITED',
          'TPM': u'TPG TELECOM LIMITED',
          'VOC': u'VOCUS COMMS LTD',
          'WTG': u'WINTECH GROUP LTD'},
 '5510': {'AEJ': u'REDBANK ENERGY LTD',
          'AES': u'ADVANCED ENERGY',
          'AGK': u'AGL ENERGY LIMITED',
          'APA': u'APA GROUP',
          'APK': u'AUSTRALIAN POWER',
          'CIF': u'CHALLENGER INFRAST.',
          'CWE': u'CARNEGIE WAVE ENERGY',
          'DUE': u'DUET GROUP',
          'EAX': u'ENERGY ACTION LTD',
          'ENB': u'ENEABBA GAS LIMITED',
          'ENE': u'ENERGY DEVELOPMENTS',
          'ENV': u'ENVESTRA LIMITED',
          'EPW': u'ERM POWER LIMITED',
          'EPX': u'ETHANE PIPELINE',
          'ERJ': u'ENERJI LTD',
          'EVM': u'ENVIROMISSION LTD',
          'EWC': u'ENERGY WORLD CORPOR.',
          'GDY': u'GEODYNAMICS LIMITED',
          'GER': u'GREENEARTH ENERGY',
          'GRK': u'GREEN ROCK ENERGY',
          'HDF': u'HASTINGS DIVERSIFIED',
          'HRL': u'HOT ROCK LIMITED',
          'IFN': u'INFIGEN ENERGY',
          'IFZ': u'INFRATIL LIMITED',
          'KEN': u'KUTH ENERGY LIMITED',
          'KTE': u'K2 ENERGY LTD',
          'PEA': u'PACIFIC ENERGY',
          'PTR': u'PETRATHERM LTD',
          'SKI': u'SPARK INFRASTRUCTURE',
          'SOO': u'SOLCO LTD',
          'SPN': u'SP AUSNET',
          'TEY': u'TORRENS ENERGY',
          'WAS': u'WASABI ENERGY LTD.',
          'WRG': u'WATER RES GRP LTD'}}
